BEGIN TRANSACTION;
INSERT INTO nodes (node_id, node_type, node_name, node_value, source_book_id, source_chapter_id) VALUES
(564, 'output_artifact', 'Knowledge Package', 'Canonical implementation-independent output format containing Identity Evidence Knowledge Relationships Validation Compilation', 40, 535),
(565, 'pipeline_stage', '7 Compiler Phases', 'Ingest Segment Extract Normalize Link Validate Emit - 7 phase compiler pipeline', 40, 536),
(566, 'core_principle', 'Evidence Rule', 'Every atom answers 6 questions: Where from What evidence Which compiler version What confidence Still current What superseded me', 40, 536),
(567, 'architecture_principle', 'Package Not Database', 'Compiler produces Knowledge Package not database. SQLite MySQL JSON BCL Neo4j Qdrant are storage backends', 40, 536),
(568, 'core_concept', 'Extraction Contract', 'Formalizes what extractor may emit - atom must contain Type Content Evidence Confidence Extraction Rule Compiler Version Source Span', 40, 538),
(569, 'pipeline_stage', 'Interpret Phase', 'Split from Extract - Candidate Atoms to Canonical Atoms. Improve interpretation without changing extraction', 40, 539),
(570, 'output_artifact', 'Compilation Manifest', 'Input Output Warnings Errors Compiler Elapsed - makes every compilation reproducible', 40, 540),
(571, 'system_component', 'Knowledge Runtime', 'Queries the Knowledge Package. Third product separate from Compiler and Package', 40, 541),
(572, 'core_concept', 'Inference Layer', 'Knowledge never explicitly stated but logically derived. Inferred atoms marked differently from extracted', 40, 543),
(573, 'core_principle', 'Extracted vs Inferred Knowledge', 'Extracted = directly compiled from source. Inferred = produced by reasoning over extracted knowledge', 40, 543),
(574, 'core_concept', 'Higher-Order Atom', 'Derived artifact from multiple base atoms instead of overwriting. Example: Definition Set from atoms 18 20 21', 40, 545),
(575, 'core_concept', 'Knowledge Hierarchies', 'Compiler builds hierarchies not just extracts. Fact to Conclusion Decision to Milestone Contradiction to Resolution', 40, 545),
(576, 'core_concept', 'Reasoning Path', 'SHOW PATH TO DECISION 44 - traverses graph from goal through reasoning to final decision. Explainable AI', 40, 546),
(577, 'architecture_principle', 'AI-Independent Architecture', 'Every consumer operates on same compiled knowledge package. ChatGPT Claude Gemini Local LLM all share', 40, 547),
(578, 'future_direction', 'Prediction Test', 'Give compiler half conversation. Predict likely contradiction before anyone says it. Tests reasoning not memory', 40, 549),
(579, 'core_concept', 'Proof Artifact', 'Assembled not extracted. Claim supported by chain of atoms. Different from Fact - proof is assembled', 40, 550),
(580, 'statistics_report', 'Compiler Quality Metrics', 'Coverage Orphans Unresolved Questions Contradictions Average Confidence - enables compiler version comparison', 40, 550),
(581, 'core_concept', 'Claim', 'Renamed from Atom. Every atom is a claim that can be supported contradicted superseded verified. Fact Decision Law Question become claim types', 40, 551),
(582, 'architecture', 'Four Layer Model', 'Layer 0 Evidence Layer 1 Claims Layer 2 Reasoning Layer 3 Knowledge. Knowledge is computed not extracted', 40, 552),
(583, 'core_concept', 'Context', 'Bounded reasoning episode with Goal Problem Decision Outcome Evidence. Preserves reasoning without forcing reconstruction', 40, 553),
(584, 'architecture', 'Five Layer Final Architecture', 'Layer 0 Evidence Layer 1 Claims Layer 2 Relations Layer 3 Episodes Layer 4 Knowledge', 40, 554),
(585, 'core_principle', 'The Invariant', 'Explainability is graph traversability. Traverse graph of claims and typed edges to reconstruct explanatory chains', 40, 556),
(586, 'future_direction', 'Reproducibility Test', 'Run automatic compiler on raw conversation. Compare output to manual graph. Metrics node match edge match missing reasoning', 40, 557),
(587, 'core_concept', 'Computable Epistemology', 'The field. Not chatbot improvement not memory systems not summarization. Structured reasoning systems', 40, 558),
(588, 'limitations', 'Circling Problem', '8 rounds of let me add one more thing and zero rounds of let me build it. Designing feels safe building feels risky', 40, 559),
(589, 'core_concept', 'Phase A Design Space Exploration', 'Ontology refinement layer definitions edge typing. Natural attractor every inconsistency generates another abstraction layer', 40, 560),
(590, 'core_concept', 'Phase B Compiler Reality Check', 'Input to output transformation deterministic extraction measurable error rates. The forcing function that breaks design loop', 40, 560),
(591, 'future_direction', 'Minimal Compiler v0', 'Hard cut scope raw conversation in claims and relations out. Naive extractor sentence to claim. Just execution', 40, 561),
(592, 'statistics_report', 'Architecture Status Table', 'Spec done 1733 lines. Proof of concept 111 atoms 80 links. Compiler contract defined not implemented. Compiler does not exist', 40, 537);
COMMIT;
