#!/usr/bin/env python3

#[@GHOST]{[@file<Config.py>][@domain<Qdrant_mysql_mlx_vector_engine>][@role<config>][@auth<devin>][@date<2026-06-27>][@ver<1.0>]}
#[@VBSTYLE]{[@auth<system>][@role<config>][@return<dict>][@no<decorators|print|hardcoded_paths>]}

"""
Gold Standard Config for Qdrant_mysql_mlx_vector_engine domain.
Auto-generated by Prj_VBScanner.
All settings in SQLite config table — key/value/description.
Env vars override SQLite values at runtime.
"""

import os
import json
import sqlite3

# ─── BASE DIR ──────────────────────────────────────────────────────────────

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_DIR = os.path.expanduser("~/.config/Qdrant_mysql_mlx_vector_engine")
os.makedirs(CONFIG_DIR, exist_ok=True)
CONFIG_DB_PATH = os.path.join(CONFIG_DIR, "Qdrant_mysql_mlx_vector_engine_config.db")

# ─── VERSIONS ──────────────────────────────────────────────────────────────

DOMAIN_VERSION = "1.0.0"
CONFIG_VERSION = "1.0.0"

# ─── CONFIG SEED SQL (embedded — no external .sql file) ────────────────────

CONFIG_SEED_SQL = """
CREATE TABLE IF NOT EXISTS config (
    key         TEXT PRIMARY KEY,
    value       TEXT,
    description TEXT
);

INSERT OR IGNORE INTO config VALUES
('domain',                  'Qdrant_mysql_mlx_vector_engine',                           'Domain name'),
('v20_db_path',             '',                                   'Path to v20_hybrid_best.db (empty = default)');
"""

# ─── ENV VAR OVERRIDE MAP ──────────────────────────────────────────────────

ENV_OVERRIDES = {
    "QDRANT_MYSQL_MLX_VECTOR_ENGINE_V20_DB_PATH":  "v20_db_path",
}


# ─── FILE INDEX ────────────────────────────────────────────────────────────
# Full index of all files in this folder. Auto-generated by Prj_VBScanner.
# Each entry is a BCL token: [@File:name]{("field";"value")...}
# DO NOT EDIT MANUALLY — run: python3 Prj_VBScanner.py /Users/wws/Qdrant_mysql_mlx_vector_engine --append-only
# BCL fields: file, purpose, classes, methods, functions, vbstyle,
#             vbstyle_passed, vbstyle_total, vbstyle_failed, bcl, bcl_headers,
#             created, modified, size, lines

FILE_INDEX = [
    "# [@File:CodeIngester_py]{(\"file\";\"CodeIngester.py\")(\"purpose\";\"#[@GHOST]{(\"file_path=/Users/wws/Qdrant_mysql_mlx_vector_engine/CodeIngester.py\";\"identity=CodeIngester\";\"purpose=Stage 1: Ingest .py files into SQLite code_graph DB. One row per method + full file ro\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"ingest_file,ingest_directory,show_status,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"7\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"state_dict,no_print\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE,FILEID,SUMMARY\")(\"created\";\"2026-06-27T10:02:18.378968\")(\"modified\";\"2026-06-27T10:02:18.378968\")(\"size\";\"17863\")(\"lines\";\"439\")}",
    "# [@File:Config_py]{(\"file\";\"Config.py\")(\"purpose\";\"Gold Standard Config for Qdrant_mysql_mlx_vector_engine domain.\")(\"classes\";\"QdrantMysqlMlxVectorEngineConfig\")(\"methods\";\"QdrantMysqlMlxVectorEngineConfig.__init__,QdrantMysqlMlxVectorEngineConfig._load,QdrantMysqlMlxVectorEngineConfig._get,QdrantMysqlMlxVectorEngineConfig.GetFileIndex,QdrantMysqlMlxVectorEngineConfig.GetFileList,QdrantMysqlMlxVectorEngineConfig.GetFileEntry\")(\"functions\";\"GetFileIndex,GetFileList,GetFileEntry\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"5\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"tuple3_return,state_dict,run_dispatch,no_self_underscore\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE\")(\"created\";\"2026-06-27T17:23:13.601995\")(\"modified\";\"2026-06-27T17:23:13.601995\")(\"size\";\"4954\")(\"lines\";\"123\")}",
    "# [@File:GraphRenderer_py]{(\"file\";\"GraphRenderer.py\")(\"purpose\";\"#[@GHOST]{(\"file_path=/Users/wws/Qdrant_mysql_mlx_vector_engine/GraphRenderer.py\";\"identity=GraphRenderer\";\"purpose=Extract all graphs from dom_graph_work.db and render them as ASCII + GraphML + PNG/S\")(\"classes\";\"GraphRenderer\")(\"methods\";\"GraphRenderer.__init__,GraphRenderer._connect,GraphRenderer._label_for,GraphRenderer._node_id,GraphRenderer.load_edges,GraphRenderer.build_graphs,GraphRenderer.build_merged_graph,GraphRenderer.render_ascii,GraphRenderer.render_hub_analysis,GraphRenderer.export_graphml,GraphRenderer.export_json,GraphRenderer.render_image,GraphRenderer.render_all_images,GraphRenderer.Run,GraphRenderer._render_all,GraphRenderer._export_all,GraphRenderer._status\")(\"functions\";\"main,load_edges,build_graphs,build_merged_graph,render_ascii,render_hub_analysis,export_graphml,export_json,render_image,render_all_images,Run\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"6\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"no_print,no_self_underscore,no_hardcoded_paths\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE,FILEID,SUMMARY\")(\"created\";\"2026-06-27T10:20:38.134768\")(\"modified\";\"2026-06-27T10:20:38.134768\")(\"size\";\"20097\")(\"lines\";\"463\")}",
    "# [@File:GraphToWizard_py]{(\"file\";\"GraphToWizard.py\")(\"purpose\";\"#[@GHOST]{(\"file_path=/Users/wws/Qdrant_mysql_mlx_vector_engine/GraphToWizard.py\";\"identity=GraphToWizard\";\"purpose=Convert dom_graph_work.db graphs into Wizard SVG Engine scene JSON, then render via \")(\"classes\";\"GraphToWizard\")(\"methods\";\"GraphToWizard.__init__,GraphToWizard._connect,GraphToWizard._label_for,GraphToWizard._node_id,GraphToWizard._status_for_type,GraphToWizard.load_graph,GraphToWizard.layout_radial,GraphToWizard.layout_tiered,GraphToWizard.build_scene_json,GraphToWizard.render_svg,GraphToWizard.Run,GraphToWizard._render,GraphToWizard._render_all\")(\"functions\";\"main,load_graph,layout_radial,layout_tiered,build_scene_json,render_svg,Run\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"6\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"no_print,no_self_underscore,no_hardcoded_paths\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE,FILEID,SUMMARY\")(\"created\";\"2026-06-27T10:24:10.448607\")(\"modified\";\"2026-06-27T10:24:10.448607\")(\"size\";\"16924\")(\"lines\";\"441\")}",
    "# [@File:SessionMiner_py]{(\"file\";\"SessionMiner.py\")(\"purpose\";\"#[@GHOST]{(\"file_path=/Users/wws/Qdrant_mysql_mlx_vector_engine/SessionMiner.py\";\"identity=SessionMiner\";\"purpose=Stage 3c: Mine devin_messages for bugs/gotchas/fixes about each method. Store as MINED\")(\"classes\";\"SessionMiner\")(\"methods\";\"SessionMiner.__init__,SessionMiner.Run,SessionMiner._p,SessionMiner.read_state,SessionMiner.set_config,SessionMiner._connect_sqlite,SessionMiner._init_schema,SessionMiner._mysql_query,SessionMiner._get_method_names,SessionMiner._search_messages,SessionMiner._extract_findings,SessionMiner.MineAll,SessionMiner.MineMethod,SessionMiner.QueryFindings,SessionMiner.Stats\")(\"functions\";\"main,Run,read_state,set_config,MineAll,MineMethod,QueryFindings,Stats\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"7\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"no_print,no_self_underscore\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE,FILEID,SUMMARY\")(\"created\";\"2026-06-27T10:57:35.974070\")(\"modified\";\"2026-06-27T10:57:35.974070\")(\"size\";\"20355\")(\"lines\";\"516\")}",
    "# [@File:StampEngine_py]{(\"file\";\"StampEngine.py\")(\"purpose\";\"#[@GHOST]{(\"file_path=/Users/wws/Qdrant_mysql_mlx_vector_engine/StampEngine.py\";\"identity=StampEngine\";\"purpose=Stage 3a: Surface stamp every METHOD unit in code_graph.db. Extract purpose, side_effect\")(\"classes\";\"StampEngine\")(\"methods\";\"StampEngine.__init__,StampEngine.Run,StampEngine._p,StampEngine.read_state,StampEngine.set_config,StampEngine._connect,StampEngine._init_schema,StampEngine._extract_purpose,StampEngine._extract_side_effects,StampEngine._extract_callers,StampEngine._compute_confidence,StampEngine._build_stamp_text,StampEngine.StampAll,StampEngine.StampUnit,StampEngine.QueryStamps,StampEngine.QueryUnstamped,StampEngine.Stats\")(\"functions\";\"main,Run,read_state,set_config,StampAll,StampUnit,QueryStamps,QueryUnstamped,Stats\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"7\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"no_print,no_self_underscore\")(\"bcl\";\"True\")(\"bcl_headers\";\"GHOST,VBSTYLE,FILEID,SUMMARY\")(\"created\";\"2026-06-27T10:54:43.322883\")(\"modified\";\"2026-06-27T10:54:43.322883\")(\"size\";\"18910\")(\"lines\";\"467\")}",
    "# [@File:agent_os_schema_py]{(\"file\";\"agent_os_schema.py\")(\"purpose\";\"Ghost: agent_os_schema\")(\"classes\";\"AgentOsSchema\")(\"methods\";\"AgentOsSchema.__init__,AgentOsSchema.Run,AgentOsSchema.Connect,AgentOsSchema._cursor,AgentOsSchema.ListTables,AgentOsSchema.DescribeTable,AgentOsSchema.GetArtifact,AgentOsSchema.InsertArtifact,AgentOsSchema.LogEvent,AgentOsSchema.read_state,AgentOsSchema.set_config\")(\"functions\";\"get_connection,Run,Connect,ListTables,DescribeTable,GetArtifact,InsertArtifact,LogEvent,read_state,set_config\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"4\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,state_dict,no_print,no_self_underscore\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:42:48.030962\")(\"modified\";\"2026-06-22T21:42:48.030962\")(\"size\";\"11696\")(\"lines\";\"294\")}",
    "# [@File:ane_diag_py]{(\"file\";\"ane_diag.py\")(\"purpose\";\"ANE Compiler Diagnostic Tool \u2014 traces what triggers ANECompilerService on macOS.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"get_process_info,get_parent_chain,system_context,top_cpu_processes,launchd_hints,live_monitor\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T17:53:59.535475\")(\"modified\";\"2026-06-22T17:53:59.535475\")(\"size\";\"4251\")(\"lines\";\"129\")}",
    "# [@File:cleanup_check_py]{(\"file\";\"cleanup_check.py\")(\"purpose\";\"(no docstring)\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T20:57:26.559408\")(\"modified\";\"2026-06-23T20:57:26.559408\")(\"size\";\"1066\")(\"lines\";\"27\")}",
    "# [@File:email_ingestion_py]{(\"file\";\"email_ingestion.py\")(\"purpose\";\"(no docstring)\")(\"classes\";\"EmailIngestion\")(\"methods\";\"EmailIngestion.__init__,EmailIngestion.SetupLogging,EmailIngestion.Run,EmailIngestion.ValidateCredentials,EmailIngestion.ConnectImap,EmailIngestion.DisconnectImap,EmailIngestion.Throttle,EmailIngestion.ConnectMysql,EmailIngestion.CloseMysql,EmailIngestion.StoreEmail,EmailIngestion.GetExistingUids,EmailIngestion.GetLastSyncDate,EmailIngestion.SaveSyncDate,EmailIngestion.QdrantRequest,EmailIngestion.EnsureQdrantCollection,EmailIngestion.GetEmbedModel,EmailIngestion.EmbedTexts,EmailIngestion.StableId,EmailIngestion.UpsertPoints,EmailIngestion.DecodeHeader,EmailIngestion.ParseEmail,EmailIngestion.ExtractBody,EmailIngestion.FetchFolder,EmailIngestion.Sync,EmailIngestion.SyncAll,EmailIngestion.Embed,EmailIngestion.Search\")(\"functions\";\"ParseArgs,Main,SetupLogging,Run,ValidateCredentials,ConnectImap,DisconnectImap,Throttle,ConnectMysql,CloseMysql,StoreEmail,GetExistingUids,GetLastSyncDate,SaveSyncDate,QdrantRequest,EnsureQdrantCollection,GetEmbedModel,EmbedTexts,StableId,UpsertPoints,DecodeHeader,ParseEmail,ExtractBody,FetchFolder,Sync,SyncAll,Embed,Search\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"7\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:48:04.895142\")(\"modified\";\"2026-06-22T21:48:04.895142\")(\"size\";\"40467\")(\"lines\";\"981\")}",
    "# [@File:embed_knowledge_base_py]{(\"file\";\"embed_knowledge_base.py\")(\"purpose\";\"(no docstring)\")(\"classes\";\"KnowledgeBaseEmbedder\")(\"methods\";\"KnowledgeBaseEmbedder.__init__,KnowledgeBaseEmbedder.Run,KnowledgeBaseEmbedder.ConnectMysql,KnowledgeBaseEmbedder.EnsureCollection,KnowledgeBaseEmbedder.LoadEmbeddedIds,KnowledgeBaseEmbedder.EmbedTable,KnowledgeBaseEmbedder.EmbedAll,KnowledgeBaseEmbedder.Count,KnowledgeBaseEmbedder.Search\")(\"functions\";\"GetModel,QdrantGet,QdrantPost,QdrantPut,StableId,CombineText,EmbedTexts,UpsertPoints,Main,Run,ConnectMysql,EnsureCollection,LoadEmbeddedIds,EmbedTable,EmbedAll,Count,Search\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"6\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:44:24.371217\")(\"modified\";\"2026-06-22T21:44:24.371217\")(\"size\";\"18491\")(\"lines\";\"478\")}",
    "# [@File:export_chat_embeddings_py]{(\"file\";\"export_chat_embeddings.py\")(\"purpose\";\"export_chat_embeddings.py \u2014 Export ALL chat history \u2192 Qdrant embeddings.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"get_model,qdrant_get,qdrant_post,qdrant_put,ensure_collection,embed_texts,upsert_points,stable_id,export_mysql_messages,parse_history_file,export_disk_history,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:41:24.734116\")(\"modified\";\"2026-06-22T21:41:24.734116\")(\"size\";\"14687\")(\"lines\";\"413\")}",
    "# [@File:export_chat_fast_py]{(\"file\";\"export_chat_fast.py\")(\"purpose\";\"export_chat_fast.py \u2014 Fast chat history \u2192 Qdrant embeddings.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"get_model,qdrant_get,qdrant_put,ensure_collection,embed_texts,upsert_points,stable_id,export_mysql_fast,parse_history_file,export_disk_fast,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"2\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print,no_hardcoded_paths\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T20:08:13.832183\")(\"modified\";\"2026-06-23T20:08:13.832183\")(\"size\";\"12112\")(\"lines\";\"360\")}",
    "# [@File:fix_rustdesk_py]{(\"file\";\"fix_rustdesk.py\")(\"purpose\";\"Fix RustDesk scaling by patching the Flutter assets to add stretch view style.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"run,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T20:43:10.182984\")(\"modified\";\"2026-06-23T20:43:10.182984\")(\"size\";\"4544\")(\"lines\";\"125\")}",
    "# [@File:install_flutter_build_py]{(\"file\";\"install_flutter_build.py\")(\"purpose\";\"Install Flutter SDK on Windows and build patched RustDesk.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"run,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T20:52:47.066188\")(\"modified\";\"2026-06-23T20:52:47.066188\")(\"size\";\"4194\")(\"lines\";\"106\")}",
    "# [@File:map_graph_units_py]{(\"file\";\"map_graph_units.py\")(\"purpose\";\"Map all graph-related code from local codebase + MySQL vb_code_test into a SQL database.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"is_graph_related,create_database,extract_from_mysql_vb_code_test,extract_from_local_codebase,insert_units,verify,main\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"2\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print,no_hardcoded_paths\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T21:24:52.188974\")(\"modified\";\"2026-06-23T21:24:52.188974\")(\"size\";\"14354\")(\"lines\";\"353\")}",
    "# [@File:system_inventory_py]{(\"file\";\"system_inventory.py\")(\"purpose\";\"Full system inventory of Windows PC for RustDesk build planning.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"ps,cmd,main,safe_int,safe_gb\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"3\")(\"vbstyle_total\";\"9\")(\"vbstyle_failed\";\"ghost_header,vbstyle_header,tuple3_return,state_dict,run_dispatch,no_print\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T21:00:10.225657\")(\"modified\";\"2026-06-23T21:00:10.225657\")(\"size\";\"9934\")(\"lines\";\"236\")}",
    "# [@File:CASCADE_SESSION_SUMMARY_md]{(\"file\";\"CASCADE_SESSION_SUMMARY.md\")(\"purpose\";\"Cascade Session Summary \u2014 Files Created & Modified\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T15:50:25.728081\")(\"modified\";\"2026-06-22T15:50:25.728081\")(\"size\";\"6174\")(\"lines\";\"72\")}",
    "# [@File:CLAUDE_md]{(\"file\";\"CLAUDE.md\")(\"purpose\";\"<!-- TASKPLANNER:START -->\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-21T18:16:11.445016\")(\"modified\";\"2026-06-21T18:16:11.445016\")(\"size\";\"3869\")(\"lines\";\"110\")}",
    "# [@File:CODE_GRAPH_md]{(\"file\";\"CODE_GRAPH.md\")(\"purpose\";\"Code Graph \u2014 Visual Diagrams\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-27T10:04:29.126814\")(\"modified\";\"2026-06-27T10:04:29.126814\")(\"size\";\"18785\")(\"lines\";\"272\")}",
    "# [@File:Config_Registry_md]{(\"file\";\"Config_Registry.md\")(\"purpose\";\"* Config Registry \u2014 All Config Files in the Workspace\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:43:39.447636\")(\"modified\";\"2026-06-22T21:43:39.447636\")(\"size\";\"28889\")(\"lines\";\"492\")}",
    "# [@File:DEVIN_WORK_LOG_md]{(\"file\";\"DEVIN_WORK_LOG.md\")(\"purpose\";\"Devin Work Log \u2014 Files Touched and Why\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T15:51:51.151461\")(\"modified\";\"2026-06-22T15:51:51.151461\")(\"size\";\"9679\")(\"lines\";\"154\")}",
    "# [@File:DevChat_Plan_md]{(\"file\";\"DevChat_Plan.md\")(\"purpose\";\"Qdrant MySQL MLX Vector Engine \u2014 Master DevChat Plan\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T22:04:42.212526\")(\"modified\";\"2026-06-22T22:04:42.212526\")(\"size\";\"26101\")(\"lines\";\"363\")}",
    "# [@File:MASTER_PLAN_AGENT_OS_md]{(\"file\";\"MASTER_PLAN_AGENT_OS.md\")(\"purpose\";\"MASTER PLAN \u2014 Database-Native Agent Operating System\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T22:03:11.547849\")(\"modified\";\"2026-06-22T22:03:11.547849\")(\"size\";\"29415\")(\"lines\";\"552\")}",
    "# [@File:PIPELINE_md]{(\"file\";\"PIPELINE.md\")(\"purpose\";\"Code Graph Pipeline \u2014 Binding Specification\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-27T10:03:23.203383\")(\"modified\";\"2026-06-27T10:03:23.203383\")(\"size\";\"12740\")(\"lines\";\"389\")}",
    "# [@File:PLAN_md]{(\"file\";\"PLAN.md\")(\"purpose\";\"Ghost \u2014 Architecture & Planning Document\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-21T18:11:01.632147\")(\"modified\";\"2026-06-21T18:11:01.632147\")(\"size\";\"72132\")(\"lines\";\"1693\")}",
    "# [@File:agent_os_schema_sql]{(\"file\";\"agent_os_schema.sql\")(\"purpose\";\"-- agent_os schema \u2014 MASTER_PLAN Phase 1\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:41:04.354767\")(\"modified\";\"2026-06-22T21:41:04.354767\")(\"size\";\"1395\")(\"lines\";\"45\")}",
    "# [@File:code_graph_db]{(\"file\";\"code_graph.db\")(\"purpose\";\"SQLite format 3\u0000\u0010\u0000\u0001\u0001\u0000@  \u0000\u0000\u0000\ufffd\u0000\u0000\u0011\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0014\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\u0000.\ufffd\u0014\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-27T11:16:15.524334\")(\"modified\";\"2026-06-27T11:16:15.524334\")(\"size\";\"18735104\")(\"lines\";\"233425\")}",
    "# [@File:com_wws_ml_lockdown_plist]{(\"file\";\"com.wws.ml-lockdown.plist\")(\"purpose\";\"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T18:01:32.902002\")(\"modified\";\"2026-06-22T18:01:32.902002\")(\"size\";\"818\")(\"lines\";\"26\")}",
    "# [@File:db_schema_rules_json]{(\"file\";\"db_schema_rules.json\")(\"purpose\";\"{\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-21T22:58:43.801598\")(\"modified\";\"2026-06-21T22:58:43.801598\")(\"size\";\"34929\")(\"lines\";\"680\")}",
    "# [@File:db_schema_rules_md]{(\"file\";\"db_schema_rules.md\")(\"purpose\";\"Relational Database Schema Design Rules \u2014 SQLite & MySQL\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-21T23:00:33.514353\")(\"modified\";\"2026-06-21T23:00:33.514353\")(\"size\";\"25875\")(\"lines\";\"193\")}",
    "# [@File:devin_rustdesk_task_txt]{(\"file\";\"devin_rustdesk_task.txt\")(\"purpose\";\"Build patched RustDesk v1.4.8 with stretch view style for Windows.\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-23T20:43:45.391317\")(\"modified\";\"2026-06-23T20:43:45.391317\")(\"size\";\"2659\")(\"lines\";\"46\")}",
    "# [@File:devin_task_codebert_router_txt]{(\"file\";\"devin_task_codebert_router.txt\")(\"purpose\";\"DEVIN TASK \u2014 CodeBERT Semantic Domain Router\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-26T10:23:43.137037\")(\"modified\";\"2026-06-26T10:23:43.137037\")(\"size\";\"5636\")(\"lines\";\"101\")}",
    "# [@File:email_ingestion_log]{(\"file\";\"email_ingestion.log\")(\"purpose\";\"2026-06-22 21:49:07,890 - email_ingestion - INFO - MySQL connected: localhost:3306/email_store\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T21:49:41.906847\")(\"modified\";\"2026-06-22T21:49:41.906847\")(\"size\";\"887\")(\"lines\";\"10\")}",
    "# [@File:error_handler_db]{(\"file\";\"error_handler.db\")(\"purpose\";\"SQLite format 3\u0000\u0010\u0000\u0001\u0001\u0000@  \u0000\u0000\u0000\t\u0000\u0000\u0000\u0007\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0003\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\t\u0000.\ufffd\u0014\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-27T15:12:51.909364\")(\"modified\";\"2026-06-27T15:12:51.909364\")(\"size\";\"28672\")(\"lines\";\"63\")}",
    "# [@File:error_log_db]{(\"file\";\"error_log.db\")(\"purpose\";\"SQLite format 3\u0000\u0010\u0000\u0001\u0001\u0000@  \u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000.\ufffd\u0014\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-27T14:31:25.651735\")(\"modified\";\"2026-06-27T14:31:25.651735\")(\"size\";\"12288\")(\"lines\";\"19\")}",
    "# [@File:integrated_app_db]{(\"file\";\"integrated_app.db\")(\"purpose\";\"SQLite format 3\u0000\u0010\u0000\u0001\u0001\u0000@  \u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000.\ufffd\u0014\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T16:43:41.682216\")(\"modified\";\"2026-06-22T16:43:41.682216\")(\"size\";\"16384\")(\"lines\";\"22\")}",
    "# [@File:mysql_concept_search_json]{(\"file\";\"mysql_concept_search.json\")(\"purpose\";\"{\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T15:26:46.565464\")(\"modified\";\"2026-06-22T15:26:46.565464\")(\"size\";\"31890660\")(\"lines\";\"1308508\")}",
    "# [@File:najma_email_architecture_brief_md]{(\"file\";\"najma_email_architecture_brief.md\")(\"purpose\";\"task##[Topic=claude_architecture_brief|Aspect=full_dense_transfer]\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T15:27:29.188392\")(\"modified\";\"2026-06-22T15:27:29.188392\")(\"size\";\"95734\")(\"lines\";\"2076\")}",
    "# [@File:najma_email_gpt_md]{(\"file\";\"najma_email_gpt.md\")(\"purpose\";\"RWhat you\u2019re describing is actually a **coherent and strong runtime\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T15:27:29.187936\")(\"modified\";\"2026-06-22T15:27:29.187936\")(\"size\";\"107372\")(\"lines\";\"2596\")}",
    "# [@File:pipeline_log]{(\"file\";\"pipeline.log\")(\"purpose\";\"[2026-06-22 16:26:06] [INFO] [init] Chat Mover v1.0.0 starting\")(\"classes\";\"\")(\"methods\";\"\")(\"functions\";\"\")(\"vbstyle\";\"False\")(\"vbstyle_passed\";\"0\")(\"vbstyle_total\";\"0\")(\"vbstyle_failed\";\"\")(\"bcl\";\"False\")(\"bcl_headers\";\"\")(\"created\";\"2026-06-22T16:28:24.185203\")(\"modified\";\"2026-06-22T16:28:24.185203\")(\"size\";\"84549\")(\"lines\";\"749\")}",
]


# ─── CONFIG CLASS ──────────────────────────────────────────────────────────

class QdrantMysqlMlxVectorEngineConfig:
    """Single source of truth for Qdrant_mysql_mlx_vector_engine configuration.

    Loads all values from SQLite config table on init.
    Env vars override SQLite values.
    """

    DOMAIN_VERSION = DOMAIN_VERSION
    FILE_INDEX = FILE_INDEX

    def __init__(self):
        self._db_path = CONFIG_DB_PATH
        self._values = {}
        self._load()

    def _load(self):
        """Load config from SQLite, apply env overrides."""
        conn = sqlite3.connect(self._db_path)
        cur = conn.cursor()
        cur.executescript(CONFIG_SEED_SQL)
        conn.commit()
        cur.execute("SELECT key, value FROM config")
        for key, value in cur.fetchall():
            self._values[key] = value
        cur.close()
        conn.close()
        for env_name, config_key in ENV_OVERRIDES.items():
            env_val = os.environ.get(env_name)
            if env_val is not None:
                self._values[config_key] = env_val

    def _get(self, key, default=None):
        return self._values.get(key, default)

    def GetFileIndex(self):
        """Return full file index for this folder — list of BCL token strings."""
        return self.FILE_INDEX

    def GetFileList(self):
        """Return just the list of filenames from BCL entries."""
        import re
        names = []
        for entry in self.FILE_INDEX:
            m = re.search(r'\("file";"([^"]+)"\)', entry)
            if m:
                names.append(m.group(1))
        return names

    def GetFileEntry(self, filename):
        """Return the BCL entry for a specific file."""
        for entry in self.FILE_INDEX:
            if '("file";"' + filename + '")' in entry:
                return entry
        return None


# ─── SINGLETON ─────────────────────────────────────────────────────────────

cfg = QdrantMysqlMlxVectorEngineConfig()
