FIND_LIST = {
    "search_term": "inram ai / efl / survivor / promote / fix / learn / error",
    "database": "vb_shared",
    "table": "code_classes",
    "total_classes_searched": 318,
    "matches": [
        {"id": 9,   "class_name": "ErrorCapture",                  "lang": "Python",     "relevance": "Captures errors to DB (type, file, function, line)"},
        {"id": 12,  "class_name": "DatabaseBrain",                 "lang": "Python",     "relevance": "DB-native AI"},
        {"id": 13,  "class_name": "CognitiveBrain",                "lang": "Python",     "relevance": "Semantic Q&A reasoning"},
        {"id": 14,  "class_name": "LearningBrain",                 "lang": "Python",     "relevance": "Self-learning: seek -> learn -> remember -> ask"},
        {"id": 15,  "class_name": "GraphBrain",                    "lang": "Python",     "relevance": "Graph-based reasoning"},
        {"id": 18,  "class_name": "ExecutionChain",                "lang": "Python",     "relevance": "Execution chain"},
        {"id": 19,  "class_name": "ReasoningGraph",                "lang": "Python",     "relevance": "Reasoning graph with uncertainty propagation"},
        {"id": 25,  "class_name": "dom_ai",                        "lang": "Python",     "relevance": "AI domain controller"},
        {"id": 65,  "class_name": "dom_rescue",                    "lang": "Python",     "relevance": "Project rescue domain"},
        {"id": 118, "class_name": "generate_vbstyle_magnetic_scaffolds", "lang": "Python", "relevance": "PYTHON SCAFFOLD GENERATOR for all magnetic engines — generates VBStyle .py versions"},
        {"id": 123, "class_name": "Lib_ConvergenceScoreEngine_v1", "lang": "C",          "relevance": "Convergence scoring engine"},
        {"id": 124, "class_name": "Lib_SurvivorSelectEngine_v1",   "lang": "C",          "relevance": "SURVIVOR SELECTION ENGINE — directly named"},
        {"id": 125, "class_name": "Lib_MagneticRelationMap_v1",    "lang": "C",          "relevance": "Magnetic relation mapping"},
        {"id": 126, "class_name": "Lib_RadiusComputeEngine_v1",    "lang": "C",          "relevance": "Radius computation"},
        {"id": 127, "class_name": "Lib_MagneticWhyFound_v1",       "lang": "C",          "relevance": "Magnetic why-found reasoning"},
        {"id": 128, "class_name": "Lib_EndCandidateEngine_v1",     "lang": "C",          "relevance": "End candidate selection"},
        {"id": 129, "class_name": "Lib_ConvergenceRunEngine_v1",   "lang": "C",          "relevance": "Convergence run engine"},
        {"id": 130, "class_name": "Lib_MagneticIndex_v1",          "lang": "C",          "relevance": "Magnetic indexing"},
        {"id": 131, "class_name": "Lib_MagneticComponent_v1",      "lang": "C",          "relevance": "Magnetic component"},
        {"id": 132, "class_name": "Core_MagneticSearch_v1",        "lang": "C",          "relevance": "Magnetic search core"},
        {"id": 134, "class_name": "Lib_ReplayMemoryEngine_v1",     "lang": "C",          "relevance": "Replay memory — past experience reuse"},
        {"id": 135, "class_name": "Lib_MagneticCanonicalMap_v1",   "lang": "C",          "relevance": "Magnetic canonical mapping"},
        {"id": 136, "class_name": "Lib_EndStateLockEngine_v1",     "lang": "C",          "relevance": "End state locking"},
        {"id": 137, "class_name": "Lib_FieldExpandEngine_v1",      "lang": "C",          "relevance": "Field expansion"},
        {"id": 138, "class_name": "Lib_EngineReport_v1",           "lang": "C",          "relevance": "Engine reporting"},
        {"id": 139, "class_name": "magnetic_runtime_unified",      "lang": "C",          "relevance": "Unified magnetic runtime"},
        {"id": 141, "class_name": "magnetic_unified",              "lang": "C",          "relevance": "Unified magnetic system"},
        {"id": 158, "class_name": "test_Lib_SurvivorSelectEngine_v1",  "lang": "C",      "relevance": "TEST for survivor selection"},
        {"id": 157, "class_name": "test_Lib_ConvergenceScoreEngine_v1","lang": "C",      "relevance": "TEST for convergence scoring"},
        {"id": 215, "class_name": "Core_Verification",             "lang": "Python",     "relevance": "Verification engine"},
        {"id": 283, "class_name": "Core_Magnetic",                 "lang": "C",          "relevance": "Magnetic core"},
        {"id": 290, "class_name": "Core_error",                    "lang": "Python",     "relevance": "Error domain"},
        {"id": 291, "class_name": "errorcodes",                    "lang": "Python",     "relevance": "Error code definitions"},
        {"id": 304, "class_name": "Core_ai",                       "lang": "Python",     "relevance": "AI core"},
        {"id": 305, "class_name": "Core_memory_bank",              "lang": "Python",     "relevance": "Memory storage"},
        {"id": 306, "class_name": "Core_ai_fix",                   "lang": "Python",     "relevance": "PROMOTE/QUARANTINE logic (promote_candidates, quarantine_first)"},
    ],
    "next_search_terms": ["ai", "neural", "model", "train", "infer", "embed", "vector", "qdrant", "search", "score", "rank", "select", "weight", "authority"],
    "search_2_term": "ai / neural / model / train / infer / embed / vector / score / rank / select / weight / authority",
    "search_2_matches": [
        {"id": 12,  "class_name": "DatabaseBrain",                  "relevance": "Database-native AI — knows schema, rules, tokens"},
        {"id": 13,  "class_name": "CognitiveBrain",                 "relevance": "Semantic Q&A reasoning, embed question, walk graph"},
        {"id": 14,  "class_name": "LearningBrain",                  "relevance": "Self-learning: seek -> learn -> remember -> ask"},
        {"id": 15,  "class_name": "GraphBrain",                     "relevance": "Experience memory: entities, concepts, relationships, clustering"},
        {"id": 18,  "class_name": "ExecutionChain",                 "relevance": "Execution chain"},
        {"id": 25,  "class_name": "dom_ai",                         "relevance": "AI domain controller — prompts, reasoning, patterns"},
        {"id": 98,  "class_name": "Gui_ai_engine",                  "lang": "Markdown",   "relevance": "GUI completeness law engine"},
        {"id": 105, "class_name": "Core_MainUnit",                  "lang": "Python",     "relevance": "Central owner with internal centers — MainUnit mirror"},
        {"id": 116, "class_name": "ai_model_training",              "lang": "Python",     "relevance": "AI model training on compressed sequences, PyTorch + Metal MPS"},
        {"id": 118, "class_name": "generate_vbstyle_magnetic_scaffolds", "lang": "Python", "relevance": "PYTHON SCAFFOLD GENERATOR — generates VBStyle .py for all magnetic engines"},
        {"id": 122, "class_name": "Lib_MagneticAuthorityWeight_v1", "lang": "C",          "relevance": "AUTHORITY WEIGHTING table for LAW, Q_A — scoring"},
        {"id": 123, "class_name": "Lib_ConvergenceScoreEngine_v1",  "lang": "C",          "relevance": "Calculate weighted fit, variance, overlap, contradiction — SCORE"},
        {"id": 124, "class_name": "Lib_SurvivorSelectEngine_v1",    "lang": "C",          "relevance": "Select and preserve TOP SURVIVORS from ranked convergence — SURVIVOR"},
        {"id": 125, "class_name": "Lib_MagneticRelationMap_v1",     "lang": "C",          "relevance": "Magnetic relation mapping"},
        {"id": 126, "class_name": "Lib_RadiusComputeEngine_v1",     "lang": "C",          "relevance": "Radius computation"},
        {"id": 127, "class_name": "Lib_MagneticWhyFound_v1",        "lang": "C",          "relevance": "Magnetic why-found reasoning"},
        {"id": 128, "class_name": "Lib_EndCandidateEngine_v1",      "lang": "C",          "relevance": "End candidate selection"},
        {"id": 129, "class_name": "Lib_ConvergenceRunEngine_v1",    "lang": "C",          "relevance": "Convergence run engine"},
        {"id": 130, "class_name": "Lib_MagneticIndex_v1",           "lang": "C",          "relevance": "Magnetic indexing"},
        {"id": 131, "class_name": "Lib_MagneticComponent_v1",       "lang": "C",          "relevance": "Magnetic component"},
        {"id": 132, "class_name": "Core_MagneticSearch_v1",         "lang": "C",          "relevance": "Magnetic search core"},
        {"id": 134, "class_name": "Lib_ReplayMemoryEngine_v1",      "lang": "C",          "relevance": "Replay memory — past experience reuse"},
        {"id": 135, "class_name": "Lib_MagneticCanonicalMap_v1",    "lang": "C",          "relevance": "Magnetic canonical mapping"},
        {"id": 136, "class_name": "Lib_EndStateLockEngine_v1",      "lang": "C",          "relevance": "End state locking"},
        {"id": 137, "class_name": "Lib_FieldExpandEngine_v1",       "lang": "C",          "relevance": "Field expansion"},
        {"id": 138, "class_name": "Lib_EngineReport_v1",            "lang": "C",          "relevance": "Engine reporting"},
        {"id": 139, "class_name": "magnetic_runtime_unified",       "lang": "C",          "relevance": "Unified magnetic runtime"},
        {"id": 141, "class_name": "magnetic_unified",               "lang": "C",          "relevance": "Unified magnetic system"},
        {"id": 151, "class_name": "test_Lib_MagneticAuthorityWeight_v1",  "lang": "C",      "relevance": "TEST for authority weighting"},
        {"id": 157, "class_name": "test_Lib_ConvergenceScoreEngine_v1",   "lang": "C",      "relevance": "TEST for convergence scoring"},
        {"id": 158, "class_name": "test_Lib_SurvivorSelectEngine_v1",     "lang": "C",      "relevance": "TEST for survivor selection"},
        {"id": 170, "class_name": "InferenceCLI",                   "lang": "Swift",     "relevance": "CLI for transformer inference (Swift)"},
        {"id": 171, "class_name": "main",                           "lang": "Swift",     "relevance": "Orchestrator entry point (Swift)"},
        {"id": 172, "class_name": "GPUModel",                       "lang": "Swift",     "relevance": "Metal GPU model (Swift)"},
        {"id": 180, "class_name": "Test_Weight_Layer",              "lang": "Swift",     "relevance": "Weight-loaded layer test (Swift/Metal)"},
        {"id": 181, "class_name": "Test_Tiny_Model",                "lang": "Swift",     "relevance": "Full tiny model end-to-end test (Swift/Metal)"},
        {"id": 184, "class_name": "Test_Chain_MultiOp",             "lang": "Swift",     "relevance": "Multi-op GPU chain test (Swift/Metal)"},
        {"id": 186, "class_name": "Test_FullModel",                 "lang": "Swift",     "relevance": "Full model inference end-to-end (Swift)"},
        {"id": 188, "class_name": "Test_WeightLoader",              "lang": "Swift",     "relevance": "Weight loader test (Swift)"},
        {"id": 192, "class_name": "Test_RealWeights",               "lang": "Swift",     "relevance": "CPU vs GPU with real checkpoint weights (Swift/Metal)"},
        {"id": 197, "class_name": "RealWeightLoader",               "lang": "Swift",     "relevance": "Loads binary checkpoint weights (Swift)"},
        {"id": 201, "class_name": "Phase1_RealWeight_ExecSpec",     "lang": "Markdown",   "relevance": "Real-weight proof execution spec"},
        {"id": 206, "class_name": "ModelWeights",                   "lang": "Swift",     "relevance": "Model weight buffers (Swift/Metal)"},
        {"id": 210, "class_name": "ModelConfig",                    "lang": "Swift",     "relevance": "Model configuration (Swift)"},
        {"id": 215, "class_name": "Core_Verification",              "lang": "Python",     "relevance": "Verification engine"},
        {"id": 283, "class_name": "Core_Magnetic",                  "lang": "C",          "relevance": "Magnetic core"},
        {"id": 290, "class_name": "Core_error",                     "lang": "Python",     "relevance": "Error domain"},
        {"id": 291, "class_name": "errorcodes",                     "lang": "Python",     "relevance": "Error code definitions"},
        {"id": 304, "class_name": "Core_ai",                        "lang": "Python",     "relevance": "AI core (dom_process.py)"},
        {"id": 305, "class_name": "Core_memory_bank",               "lang": "Python",     "relevance": "Memory storage"},
        {"id": 306, "class_name": "Core_ai_fix",                    "lang": "Python",     "relevance": "PROMOTE/QUARANTINE logic (promote_candidates, quarantine_first)"},
    ],

    # =========================================================
    # LANGUAGE DETECTION SUMMARY
    # =========================================================
    "language_summary": {
        "Python":  {"count": 18, "note": "VBStyle compliant, methods extracted by AST, has Run() + Tuple3"},
        "C":       {"count": 22, "note": "C code with VBStyle GHOST headers. AST cannot extract methods. Use generate_vbstyle_magnetic_scaffolds (id=118) to generate Python .py versions"},
        "Swift":   {"count": 10, "note": "Metal/GPU inference code. AST cannot extract methods. Would need Swift parser or Python wrapper"},
        "Markdown": {"count": 2, "note": "Text/documentation, not code. No methods to extract"},
    },

    # =========================================================
    # KEY FINDING: Python scaffold generator exists
    # =========================================================
    "python_scaffold_generator": {
        "id": 118,
        "class_name": "generate_vbstyle_magnetic_scaffolds",
        "lang": "Python",
        "purpose": "Generates VBStyle Python .py scaffold files for ALL magnetic engines",
        "scaffold_specs": [
            "Lib_FieldExpandEngine",
            "Lib_RadiusComputeEngine",
            "Lib_ConvergenceScoreEngine",
            "Lib_SurvivorSelectEngine",
            "Lib_ReplayMemoryEngine",
            "Lib_EndStateLockEngine",
            "Lib_EndCandidateEngine",
            "Lib_ConvergenceRunEngine",
        ],
        "note": "This is the Python version of the C magnetic engines. Run this generator to create .py files, then ingest those into EFL DB."
    },

    # =========================================================
    # NOTES FOR NEXT TIME
    # =========================================================
    "notes": [
        "C classes (Lib_*, magnetic_*, Core_Magnetic*) have VBStyle GHOST headers but C bodies — AST parser gives 0 methods",
        "Swift classes (GPU*, Test_*, Real*, Model*, InferenceCLI, main) are Metal GPU code — AST parser gives 0 methods",
        "Python scaffold generator (id=118) can create .py versions of all magnetic engines — use it to get VBStyle Python classes into EFL DB",
        "Next step: run generate_vbstyle_magnetic_scaffolds to create .py files, then ingest into EFL DB so methods can be extracted",
        "For Swift: would need a Swift function parser (regex-based) or rewrite as Python wrappers",
        "Language detection rule: check first 500 chars of class_code for #include (C), import Foundation/MTL (Swift), def/class (Python), #@GHOST+def (Python VBStyle)",
    ]
}
