#!/usr/bin/env python3
"""
Normalizer: takes Level-1 documentation closure (EXTRACTED_DOMAINS) and produces
a Level-2 normalized closure with:
  - Merged overlapping domains
  - Collapsed shared primitives (report, validate, list, etc.)
  - Alias groups resolved to canonical names
  - True unique behavior count
  - Survivor ranking placeholder

Output: normalized_domain_closure.py
"""
import keyword, os, importlib.util
from collections import defaultdict, Counter

# Load Level-1 data
spec = importlib.util.spec_from_file_location("der",
    os.path.join(os.path.dirname(__file__), "domain_extraction_results.py"))
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
EXTRACTED_DOMAINS = mod.EXTRACTED_DOMAINS

# ============================================================
# 1. DOMAIN MERGE MAP
# Pairs with Jaccard > 0.15 that represent the same concept.
# ============================================================
MERGE_MAP = {
    # wws_index absorbed into index (92.9% overlap)
    "wws_index": "index",
    # log absorbed into logging (same concept)
    "log": "logging",
    # audit absorbed into governance (same concept, governance is broader)
    "audit": "governance",
    # folder absorbed into fileops (file vs dir, same ops)
    "folder": "fileops",
    # ingest_cli and ingest_gui absorbed into ingest (same domain, different UI)
    "ingest_cli": "ingest",
    "ingest_gui": "ingest",
}

# ============================================================
# 2. SHARED PRIMITIVES
# Methods that appear in 5+ domains are NOT domain-specific.
# They get extracted into a SHARED_PRIMITIVES layer.
# ============================================================
SHARED_PRIMITIVE_THRESHOLD = 5  # appears in >= 5 domains -> shared

# ============================================================
# 3. ALIAS RESOLUTION
# Canonical name for alias groups.
# ============================================================
ALIAS_CANONICAL = {
    # extract family
    "extract_class": "extract",
    "extract_code": "extract",
    "extract_constants": "extract",
    "extract_docstring": "extract",
    "extract_header": "extract",
    "extract_imports": "extract",
    "extract_jumps": "extract",
    "extract_metadata": "extract",
    "extract_method": "extract",
    "extract_names": "extract",
    "extract_opcodes": "extract",
    "extract_registers": "extract",
    "extract_substrings": "extract",
    # set family
    "set_style": "set",
    "set_theme": "set",
    "set_title": "set",
    "settings": "set",
    "setup": "set",
    # read family
    "read_brackets": "read",
    "read_header": "read",
    "readlines": "read",
    "readme": "read",
    # create family
    "create_index": "create",
    "create_table": "create",
    "create_widget": "create",
    "create_window": "create",
    # query family
    "query_concept": "query",
    "query_fact": "query",
    "query_relation": "query",
    "query_rule": "query",
    # split family
    "split_class": "split",
    "split_method": "split",
    "splitter": "split",
    # remove family
    "remove_edge": "remove",
    "remove_node": "remove",
    "remove_widget": "remove",
    # list family
    "listdir": "list",
    "listen": "list",
    # count family
    "count_classes": "count",
    "count_methods": "count",
    # get family
    "get_edge": "get",
    "get_node": "get",
    # write family
    "writelines": "write",
    # connect family
    "connected": "connect",
    # validate family
    "validate_brackets": "validate",
    # check family -> validate
    "check_headers": "validate",
    "check_naming": "validate",
    "check_state": "validate",
    "check_run": "validate",
    "check_tuple3": "validate",
    "check_no_print": "validate",
    "check_no_decorator": "validate",
    "check_no_hardcode": "validate",
    "check_pascal": "validate",
    "check_ghost": "validate",
    "check_vbstyle": "validate",
    "check_init": "validate",
    "check_self_state": "validate",
    "check_dispatch": "validate",
    "check_format": "validate",
    "check_structure": "validate",
    "check_header": "validate",
    "check_class": "validate",
    "check_method": "validate",
    "fix_header": "fix",
    "fix_naming": "fix",
    "fix_format": "fix",
    # event family -> dispatch
    "event_click": "dispatch",
    "event_key": "dispatch",
    "event_mouse": "dispatch",
    "event_resize": "dispatch",
    "event_close": "dispatch",
    # draw family -> render
    "draw_line": "render",
    "draw_rect": "render",
    "draw_text": "render",
    # add family
    "add_fact": "add",
    "add_rule": "add",
    "add_concept": "add",
    "add_relation": "add",
    "add_node": "add",
    "add_edge": "add",
    "add_widget": "add",
    "add_job": "add",
    "add_tool": "add",
    # to_ family -> convert
    "to_json": "convert",
    "from_json": "convert",
    "to_yaml": "convert",
    "from_yaml": "convert",
    "to_xml": "convert",
    "from_xml": "convert",
    "to_csv": "convert",
    "from_csv": "convert",
    "to_toml": "convert",
    "to_dict": "convert",
    "to_list": "convert",
    "to_text": "convert",
    # bulk_ family
    "bulk_insert": "insert",
    # url_ family
    "url_encode": "encode",
    "url_decode": "decode",
    # event_ family
    "focusInEvent": "dispatch",
    "focusOutEvent": "dispatch",
    "keyPressEvent": "dispatch",
    "mousePressEvent": "dispatch",
    # db ops
    "drop_table": "delete",
    "alter_table": "update",
    "upsert": "insert",
    "select": "query",
    # ingest variants
    "browse": "scan",
    "select_files": "scan",
    # misc
    "deadletter": "queue",
    "nack": "ack",
    "unsubscribe": "subscribe",
    "decompress": "compress",
    "decompile": "compile",
    "disassemble": "assemble",
    "untokenize": "tokenize",
    "filterfalse": "filter",
    "dropwhile": "filter",
    "starmap": "map",
    "filterfalse": "filter",
    "shortest_path": "path",
    "bfs": "traverse",
    "dfs": "traverse",
    "connected": "traverse",
    "components": "traverse",
    "topology": "sort",
    "cycles": "detect",
    "anomaly": "detect",
    "drift": "detect",
    "flag": "detect",
    "violation": "detect",
    "compliance": "verify",
    "baseline": "init",
    "calibrate": "init",
    "defaults": "init",
    "prototype": "create",
    "clone": "copy",
    "dispose": "delete",
    "unregister": "register",
    "forget": "delete",
    "recall": "get",
    "persist": "save",
    "snapshot": "save",
    "invalidate": "delete",
    "refresh": "update",
    "expire": "delete",
    "cache_info": "stats",
    "cache_clear": "clear",
    "weakref": "get",
    "roundtrip": "verify",
    "waypoint": "set",
    "landmark": "search",
    "orient": "set",
    "heading": "get",
    "survey": "scan",
    "cross_reference": "link",
    "label_map": "build",
    "function_map": "build",
    "lockout": "lock",
    "revoke": "delete",
    "permission": "authorize",
    "role": "authorize",
    "policy": "set",
    "rule": "set",
    "constraint": "set",
    "waive": "delete",
    "approve": "verify",
    "reject": "verify",
    "review": "scan",
    "exception": "handle",
    "escalate": "handle",
    "rollback": "restore",
    "quarantine": "isolate",
    "diagnose": "analyze",
    "repair": "fix",
    "clean": "delete",
    "touch": "create",
    "temp": "create",
    "makedirs": "create",
    "rmdir": "delete",
    "walk": "scan",
    "glob": "search",
    "chmod": "set",
    "stat": "stats",
    "exists": "verify",
    "resolve": "normalize",
    "rename": "update",
    "move": "update",
    "copy": "copy",
    "append": "write",
    "truncate": "delete",
    "seek": "set",
    "tell": "get",
    "flush": "sync",
    "lock": "lock",
    "watch": "monitor",
    "reload": "load",
    "environment": "load",
    "profile": "monitor",
    "sandbox": "isolate",
    "hook": "register",
    "intercept": "register",
    "dispatch": "dispatch",
    "eval": "execute",
    "benchmark": "test",
    "fixture": "create",
    "mock": "create",
    "coverage": "stats",
    "skip": "control",
    "integration": "test",
    "unit": "test",
    "assert": "verify",
    "teardown": "delete",
    "chain": "link",
    "branch": "route",
    "loop": "iterate",
    "condition": "verify",
    "wait": "sync",
    "notify": "send",
    "webhook": "register",
    "cron": "schedule",
    "interval": "schedule",
    "once": "schedule",
    "recurring": "schedule",
    "state_machine": "run",
    "pipeline": "run",
    "sequence": "run",
    "parallel": "run",
    "retry": "run",
    "timeout": "set",
    "dependency": "link",
    "priority": "set",
    "queue": "queue",
    "worker": "run",
    "submit": "send",
    "pause": "control",
    "resume": "control",
    "start": "start",
    "stop": "stop",
    "kill": "stop",
    "signal": "send",
    "stdin": "write",
    "stdout": "read",
    "stderr": "read",
    "pid": "get",
    "restart": "run",
    "metric": "log",
    "event": "dispatch",
    "trace": "log",
    "rotate": "archive",
    "purge": "delete",
    "tail": "read",
    "follow": "read",
    "level": "set",
    "category": "set",
    "cross_ref": "link",
    "changelog": "report",
    "api_doc": "generate",
    "example": "generate",
    "diagram": "generate",
    "render": "render",
    "template": "set",
    "depend": "stats",
    "lock": "lock",
    "publish": "send",
    "subscribe": "subscribe",
    "broadcast": "send",
    "ack": "ack",
    "delay": "set",
    "channel": "set",
    "topic": "set",
    "prompt": "set",
    "complete": "generate",
    "generate": "generate",
    "summarize": "generate",
    "translate": "convert",
    "plan": "plan",
    "reason": "reason",
    "reflect": "reflect",
    "evaluate": "evaluate",
    "learn": "learn",
    "remember": "store",
    "classify": "classify",
    "route": "route",
    "fallback": "fallback",
    "explain": "explain",
    "score": "score",
    "confidence": "get",
    "feedback": "send",
    "tune": "set",
    "ask": "send",
    "answer": "generate",
    "embed": "embed",
    "rank": "sort",
    "facet": "filter",
    "suggest": "generate",
    "autocomplete": "generate",
    "highlight": "render",
    "snippet": "extract",
    "fuzzy": "search",
    "regex": "search",
    "phrase": "search",
    "vector": "search",
    "similarity": "search",
    "nearest": "search",
    "reindex": "rebuild",
    "match": "search",
    "rebuild": "rebuild",
    "index": "index",
    "build": "build",
    "neighbors": "get",
    "path": "path",
    "traverse": "traverse",
    "visualize": "render",
    "navigate": "route",
    "distance": "calculate",
    "route": "route",
    "map": "generate",
    "explore": "scan",
    "inspect": "get",
    "describe": "stats",
    "schema": "stats",
    "tables": "list",
    "columns": "list",
    "indexes": "list",
    "constraints": "list",
    "foreign_keys": "list",
    "triggers": "list",
    "stored_procs": "list",
    "views": "list",
    "functions": "list",
    "relationships": "list",
    "discover": "scan",
    "introspect": "scan",
    "design": "design",
    "edit": "update",
    "compare": "compare",
    "sync": "sync",
    "monitor": "monitor",
    "enrich": "update",
    "tag": "set",
    "store": "store",
    "dedupe": "filter",
    "standardize": "normalize",
    "aggregate": "aggregate",
    "group": "group",
    "pivot": "transform",
    "trend": "calculate",
    "forecast": "predict",
    "correlate": "calculate",
    "cluster": "classify",
    "insight": "report",
    "sum": "calculate",
    "avg": "calculate",
    "min": "calculate",
    "max": "calculate",
    "median": "calculate",
    "stddev": "calculate",
    "normalize": "normalize",
    "format": "format",
    "clean": "delete",
    "enrich": "update",
    "project": "transform",
    "rename": "update",
    "restructure": "transform",
    "flatten": "transform",
    "accumulate": "aggregate",
    "compress_data": "compress",
    "starmap": "map",
    "tokenize": "tokenize",
    "lex": "tokenize",
    "emit": "generate",
    "transform_ast": "transform",
    "read_header": "read",
    "extract_metadata": "extract",
    "split_class": "split",
    "split_method": "split",
    "extract_docstring": "extract",
    "untokenize": "tokenize",
    "hash": "hash",
    "encrypt": "encrypt",
    "decrypt": "decrypt",
    "authenticate": "authenticate",
    "authorize": "authorize",
    "sign": "sign",
    "token": "generate",
    "refresh_token": "update",
    "reset": "delete",
    "restore": "restore",
    "backup": "backup",
    "recover": "recover",
    "isolate": "isolate",
    "handle": "handle",
    "analyze": "analyze",
    "fix": "fix",
    "control": "control",
    "iterate": "iterate",
    "predict": "predict",
    "calculate": "calculate",
    "copy": "copy",
    "save": "save",
    "load": "load",
    "clear": "clear",
    "stats": "stats",
    "keys": "list",
    "size": "get",
    "sync": "sync",
    "archive": "archive",
    "compare": "compare",
    "diff": "compare",
    "search": "search",
    "replace": "replace",
    "join": "join",
    "encode": "encode",
    "decode": "decode",
    "serialize": "serialize",
    "deserialize": "deserialize",
    "checksum": "hash",
    "base64": "encode",
    "hex": "encode",
    "parse": "parse",
    "validate": "validate",
    "verify": "verify",
    "report": "report",
    "scan": "scan",
    "enforce": "enforce",
    "create": "create",
    "delete": "delete",
    "update": "update",
    "insert": "insert",
    "get": "get",
    "set": "set",
    "read": "read",
    "write": "write",
    "list": "list",
    "export": "export",
    "import": "import",
    "query": "query",
    "merge": "merge",
    "filter": "filter",
    "sort": "sort",
    "add": "add",
    "remove": "remove",
    "start": "start",
    "stop": "stop",
    "run": "run",
    "execute": "execute",
    "compile": "compile",
    "assemble": "assemble",
    "log": "log",
    "debug": "log",
    "info": "log",
    "warn": "log",
    "error": "log",
    "fatal": "log",
    "generate": "generate",
    "render": "render",
    "dispatch": "dispatch",
    "connect": "connect",
    "disconnect": "disconnect",
    "send": "send",
    "recv": "receive",
    "receive": "receive",
    "get_request": "request",
    "post": "request",
    "put": "request",
    "patch": "request",
    "delete_request": "request",
    "upload": "send",
    "download": "receive",
    "stream": "stream",
    "websocket": "connect",
    "poll": "monitor",
    "resolve_dns": "resolve",
    "ping": "test",
    "trace_route": "trace",
    "schedule": "schedule",
    "cancel": "cancel",
    "pause": "control",
    "resume": "control",
    "next": "get",
    "history": "list",
    "info": "get",
    "cpu": "get",
    "memory": "get",
    "disk": "get",
    "network_info": "get",
    "hostname": "get",
    "processes": "list",
    "uptime": "get",
    "load_avg": "get",
    "users": "list",
    "env": "get",
    "platform": "get",
    "monitor": "monitor",
    "report": "report",
    "open": "open",
    "close": "close",
    "seek": "set",
    "tell": "get",
    "flush": "sync",
    "truncate": "delete",
    "readlines": "read",
    "writelines": "write",
    "stat": "stats",
    "exists": "verify",
    "chmod": "set",
    "glob": "search",
    "copy": "copy",
    "move": "update",
    "rename": "update",
    "resolve_path": "normalize",
    "append": "write",
    "touch": "create",
    "delete_file": "delete",
    "listdir": "list",
    "walk": "scan",
    "makedirs": "create",
    "rmdir": "delete",
    "compress_file": "compress",
    "decompress_file": "decompress",
    "split_path": "split",
    "join_path": "join",
    "lock_file": "lock",
    "scan_dir": "scan",
    "watch_fs": "monitor",
    "temp_file": "create",
    "connect_db": "connect",
    "disconnect_db": "disconnect",
    "execute_sql": "execute",
    "commit": "commit",
    "rollback": "rollback",
    "fetch": "fetch",
    "create_table": "create",
    "drop_table": "delete",
    "alter_table": "update",
    "create_index_db": "create",
    "insert_row": "insert",
    "select_rows": "query",
    "update_rows": "update",
    "delete_rows": "delete",
    "upsert_row": "insert",
    "bulk_insert_rows": "insert",
    "query_db": "query",
    "transaction": "transaction",
    "backup_db": "backup",
    "restore_db": "restore",
    "migrate_db": "migrate",
    "schema_info": "stats",
    "describe_table": "stats",
    "count_rows": "count",
    "exists_row": "verify",
    "vacuum": "optimize",
    "optimize_query": "optimize",
    "show_window": "show",
    "close_window": "close",
    "show_widget": "show",
    "hide_widget": "hide",
    "resize_widget": "update",
    "set_title": "set",
    "add_widget": "add",
    "remove_widget": "remove",
    "set_layout": "set",
    "set_style": "set",
    "set_theme": "set",
    "button": "create",
    "label": "create",
    "text_input": "create",
    "checkbox": "create",
    "combo": "create",
    "list_widget": "create",
    "table_widget": "create",
    "tree_widget": "create",
    "tab_widget": "create",
    "splitter_widget": "create",
    "slider_widget": "create",
    "progress_bar": "create",
    "menu_bar": "create",
    "toolbar": "create",
    "dialog": "create",
    "panel": "create",
    "render_widget": "render",
    "update_display": "update",
    "refresh": "update",
    "paint_event": "render",
    "create_widget": "create",
    "enable": "set",
    "disable": "set",
    "tooltip": "set",
    "menu": "create",
    "signal": "dispatch",
    "slot": "dispatch",
    "connect_signal": "connect",
    "disconnect_signal": "disconnect",
    "paint": "render",
    "event": "dispatch",
    "index_doc": "index",
    "search_index": "search",
    "query_index": "query",
    "update_doc": "update",
    "delete_doc": "delete",
    "optimize_index": "optimize",
    "rebuild_index": "rebuild",
    "stats_index": "stats",
    "export_index": "export",
    "import_index": "import",
    "merge_index": "merge",
    "split_index": "split",
    "validate_index": "validate",
    "scan_sources": "scan",
    "parse_data": "parse",
    "load_data": "load",
    "validate_data": "validate",
    "extract_data": "extract",
    "transform_data": "transform",
    "dedupe_data": "filter",
    "enrich_data": "update",
    "classify_data": "classify",
    "tag_data": "set",
    "store_data": "store",
    "index_data": "index",
    "report_ingest": "report",
    "schedule_ingest": "schedule",
    "batch_ingest": "run",
    "status_ingest": "get",
    "report_cli": "report",
    "resume_ingest": "control",
    "cancel_ingest": "cancel",
    "preview": "read",
    "progress": "get",
    "history_ingest": "list",
    "report_gui": "report",
    "validate_gui": "validate",
    "cancel_gui": "cancel",
    "write_log": "write",
    "read_log": "read",
    "query_log": "query",
    "filter_log": "filter",
    "search_log": "search",
    "format_log": "format",
    "set_level": "set",
    "set_category": "set",
    "export_log": "export",
    "rotate_log": "archive",
    "archive_log": "archive",
    "purge_log": "delete",
    "tail_log": "read",
    "follow_log": "read",
    "log_msg": "log",
    "debug": "log",
    "info": "log",
    "warn": "log",
    "error": "log",
    "fatal": "log",
    "trace_exec": "log",
    "metric": "log",
    "event_log": "dispatch",
    "filter_records": "filter",
    "query_entries": "query",
    "flush_handlers": "sync",
    "rotate_files": "archive",
    "archive_logs": "archive",
    "generate_docs": "generate",
    "render_docs": "render",
    "template_docs": "set",
    "export_docs": "export",
    "import_docs": "import",
    "index_docs": "index",
    "search_docs": "search",
    "cross_ref": "link",
    "changelog": "report",
    "readme": "generate",
    "api_doc": "generate",
    "example": "generate",
    "diagram": "generate",
    "build_pkg": "build",
    "install": "install",
    "uninstall": "delete",
    "update_pkg": "update",
    "list_pkgs": "list",
    "info_pkg": "get",
    "depend": "stats",
    "resolve_deps": "resolve",
    "lock_deps": "lock",
    "publish": "send",
    "fetch": "fetch",
    "verify_pkg": "verify",
    "sign_pkg": "sign",
    "checksum": "hash",
    "trigger_job": "run",
    "schedule_task": "schedule",
    "run_task": "run",
    "chain_tasks": "link",
    "branch_cond": "route",
    "loop_items": "iterate",
    "cond_exec": "verify",
    "wait_cond": "sync",
    "notify": "send",
    "webhook": "register",
    "cron_sched": "schedule",
    "interval_sched": "schedule",
    "event_trigger": "dispatch",
    "state_machine": "run",
    "create_archive": "create",
    "extract_archive": "extract",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "list_archive": "list",
    "verify_archive": "verify",
    "split_archive": "split",
    "join_archive": "join",
    "encrypt_archive": "encrypt",
    "decrypt_archive": "decrypt",
    "index_archive": "index",
    "search_archive": "search",
    "scan_violations": "scan",
    "check_compliance": "verify",
    "report_audit": "report",
    "record_violation": "log",
    "check_status": "verify",
    "trace_audit": "trace",
    "history_audit": "list",
    "diff_audit": "compare",
    "set_baseline": "set",
    "detect_drift": "detect",
    "flag_activity": "detect",
    "escalate_finding": "handle",
    "fix_violation": "fix",
    "verify_fix": "verify",
    "check_naming": "validate",
    "check_format": "validate",
    "check_structure": "validate",
    "report_style": "report",
    "check_vbstyle": "validate",
    "fix_header": "fix",
    "fix_naming": "fix",
    "fix_format": "fix",
    "enforce_style": "enforce",
    "scan_style": "scan",
    "score_style": "score",
    "design_arch": "design",
    "review_arch": "review",
    "scan_arch": "scan",
    "pattern": "analyze",
    "layer": "analyze",
    "dependency": "analyze",
    "coupling": "calculate",
    "cohesion": "calculate",
    "complexity": "calculate",
    "technical_debt": "calculate",
    "approve_arch": "verify",
    "enforce_arch": "enforce",
    "document_arch": "generate",
    "report_arch": "report",
    "baseline_arch": "set",
    "disassemble": "disassemble",
    "assemble": "assemble",
    "decode_instr": "decode",
    "encode_instr": "encode",
    "analyze_asm": "analyze",
    "extract_opcodes": "extract",
    "extract_registers": "extract",
    "extract_jumps": "extract",
    "label_map": "build",
    "function_map": "build",
    "cross_reference": "link",
    "report_asm": "report",
    "compile_bc": "compile",
    "disassemble_bc": "disassemble",
    "analyze_bc": "analyze",
    "decompile_bc": "decompile",
    "extract_constants": "extract",
    "extract_names": "extract",
    "extract_code": "extract",
    "optimize_bc": "optimize",
    "patch_bc": "update",
    "inject_bc": "insert",
    "verify_bc": "verify",
    "compare_bc": "compare",
    "parse_args": "parse",
    "help": "report",
    "version": "get",
    "run_cli": "run",
    "parse_flags": "parse",
    "parse_options": "parse",
    "dispatch_cmd": "dispatch",
    "complete": "generate",
    "history_cli": "list",
    "alias": "set",
    "pipe": "send",
    "redirect": "set",
    "signal_cli": "send",
    "exit": "close",
    "encode_data": "encode",
    "decode_data": "decode",
    "serialize_obj": "serialize",
    "deserialize_obj": "deserialize",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "hash_data": "hash",
    "checksum": "hash",
    "base64_codec": "encode",
    "hex_codec": "encode",
    "url_encode": "encode",
    "url_decode": "decode",
    "validate_encoded": "validate",
    "build_graph": "build",
    "query_graph": "query",
    "traverse_graph": "traverse",
    "neighbors": "get",
    "find_path": "path",
    "shortest_path": "path",
    "find_cycles": "detect",
    "check_connected": "verify",
    "components": "list",
    "topology": "sort",
    "visualize_graph": "render",
    "export_graph": "export",
    "import_graph": "import",
    "merge_graphs": "merge",
    "navigate_to": "route",
    "calc_distance": "calculate",
    "calc_route": "route",
    "orient_dir": "set",
    "get_heading": "get",
    "find_landmark": "search",
    "manage_waypoints": "set",
    "explore_area": "scan",
    "generate_map": "generate",
    "survey_area": "scan",
    "report_nav": "report",
    "calibrate_compass": "init",
    "benchmark_nav": "test",
    "to_json": "convert",
    "from_json": "convert",
    "to_yaml": "convert",
    "from_yaml": "convert",
    "to_xml": "convert",
    "from_xml": "convert",
    "to_csv": "convert",
    "from_csv": "convert",
    "to_toml": "convert",
    "to_dict": "convert",
    "to_list": "convert",
    "to_text": "convert",
    "validate_conv": "validate",
    "roundtrip": "verify",
    "split_code": "split",
    "extract_class": "extract",
    "extract_method": "extract",
    "merge_code": "merge",
    "extract_imports": "extract",
    "extract_header": "extract",
    "count_classes": "count",
    "count_methods": "count",
    "validate_split": "validate",
    "report_split": "report",
    "create_ctx": "create",
    "execute_kernel": "execute",
    "destroy_ctx": "delete",
    "list_devices": "list",
    "inspect_obj": "get",
    "register_mod": "register",
    "unregister_mod": "unregister",
    "status_cu": "get",
    "history_cu": "list",
    "report_cu": "report",
    "validate_cu": "validate",
    "benchmark_cu": "test",
    "discover_schemas": "scan",
    "introspect_db": "scan",
    "schema_info": "stats",
    "list_tables": "list",
    "list_columns": "list",
    "list_indexes": "list",
    "list_constraints": "list",
    "list_foreign_keys": "list",
    "list_triggers": "list",
    "list_stored_procs": "list",
    "list_views": "list",
    "list_functions": "list",
    "list_relationships": "list",
    "report_inv": "report",
    "connect_studio": "connect",
    "query_studio": "query",
    "browse_db": "scan",
    "edit_data": "update",
    "design_schema": "design",
    "migrate_studio": "migrate",
    "compare_schemas": "compare",
    "sync_dbs": "sync",
    "export_data": "export",
    "import_data": "import",
    "visualize_schema": "render",
    "optimize_queries": "optimize",
    "monitor_db": "monitor",
    "report_studio": "report",
    "create_obj": "create",
    "register_type": "register",
    "get_type": "get",
    "unregister_type": "unregister",
    "list_types": "list",
    "prototype_obj": "create",
    "clone_obj": "copy",
    "configure_factory": "set",
    "dispose_obj": "delete",
    "validate_factory": "validate",
    "report_factory": "report",
    "read_bytes": "read",
    "write_bytes": "write",
    "close_fd": "close",
    "stat_file": "stats",
    "chmod_file": "set",
    "exists_path": "verify",
    "append_file": "write",
    "copy_file": "copy",
    "move_file": "update",
    "rename_file": "update",
    "glob_files": "search",
    "walk_tree": "scan",
    "touch_file": "create",
    "delete_file": "delete",
    "temp_file": "create",
    "split_path": "split",
    "join_path": "join",
    "create_dir": "create",
    "delete_dir": "delete",
    "list_dir": "list",
    "walk_dir": "scan",
    "size_dir": "get",
    "tree_dir": "generate",
    "move_dir": "update",
    "copy_dir": "copy",
    "rename_dir": "update",
    "watch_dir": "monitor",
    "sync_dirs": "sync",
    "archive_dir": "archive",
    "compare_dirs": "compare",
    "clean_dir": "delete",
    "add_node": "add",
    "add_edge": "add",
    "remove_node": "remove",
    "remove_edge": "remove",
    "get_node": "get",
    "get_edge": "get",
    "find_path": "path",
    "traverse_graph": "traverse",
    "dfs": "traverse",
    "bfs": "traverse",
    "shortest_path": "path",
    "find_cycles": "detect",
    "topological_sort": "sort",
    "visualize_graph": "render",
    "export_graph": "export",
    "create_index": "create",
    "build_index": "build",
    "search_index": "search",
    "query_index": "query",
    "update_index": "update",
    "delete_index": "delete",
    "optimize_index": "optimize",
    "rebuild_index": "rebuild",
    "stats_index": "stats",
    "export_index": "export",
    "import_index": "import",
    "merge_index": "merge",
    "split_index": "split",
    "validate_index": "validate",
    "scan_sources": "scan",
    "parse_data": "parse",
    "load_data": "load",
    "validate_data": "validate",
    "extract_data": "extract",
    "transform_data": "transform",
    "dedupe_data": "filter",
    "enrich_data": "update",
    "classify_data": "classify",
    "tag_data": "set",
    "store_data": "store",
    "index_data": "index",
    "report_ingest": "report",
    "schedule_ingest": "schedule",
    "batch_ingest": "run",
    "status_ingest": "get",
    "report_cli": "report",
    "resume_ingest": "control",
    "cancel_ingest": "cancel",
    "browse_files": "scan",
    "select_files": "scan",
    "import_gui": "import",
    "preview_data": "read",
    "show_progress": "get",
    "set_settings": "set",
    "view_history": "list",
    "report_gui": "report",
    "validate_gui": "validate",
    "cancel_gui": "cancel",
    "write_entry": "write",
    "read_entries": "read",
    "query_entries": "query",
    "filter_entries": "filter",
    "search_entries": "search",
    "format_entries": "format",
    "set_level": "set",
    "set_category": "set",
    "export_log": "export",
    "rotate_files": "archive",
    "archive_logs": "archive",
    "purge_entries": "delete",
    "tail_log": "read",
    "follow_log": "read",
    "add_fact": "add",
    "query_fact": "query",
    "add_rule": "add",
    "query_rule": "query",
    "add_concept": "add",
    "query_concept": "query",
    "add_relation": "add",
    "query_relation": "query",
    "infer": "infer",
    "explain": "explain",
    "prove": "verify",
    "disprove": "verify",
    "merge_graphs": "merge",
    "export_graph": "export",
    "import_graph": "import",
    "set_confidence": "set",
    "track_source": "set",
    "hash_data": "hash",
    "encrypt_data": "encrypt",
    "decrypt_data": "decrypt",
    "authenticate_user": "authenticate",
    "authorize_user": "authorize",
    "sign_data": "sign",
    "verify_sig": "verify",
    "generate_token": "generate",
    "refresh_token": "update",
    "revoke_token": "delete",
    "check_permission": "authorize",
    "manage_roles": "set",
    "define_policy": "set",
    "audit_events": "log",
    "lockout_user": "lock",
    "reset_creds": "delete",
    "start_task": "start",
    "stop_task": "stop",
    "dispatch_task": "dispatch",
    "submit_task": "send",
    "pause_exec": "control",
    "resume_exec": "control",
    "schedule_task": "schedule",
    "pipeline_exec": "run",
    "sequence_exec": "run",
    "parallel_exec": "run",
    "retry_task": "run",
    "set_timeout": "set",
    "manage_deps": "link",
    "set_priority": "set",
    "manage_queue": "queue",
    "manage_worker": "run",
    "get_status": "get",
    "load_config": "load",
    "save_config": "save",
    "get_config": "get",
    "set_config": "set",
    "list_sections": "list",
    "delete_key": "delete",
    "validate_config": "validate",
    "merge_configs": "merge",
    "export_config": "export",
    "import_config": "import",
    "get_defaults": "get",
    "load_profile": "load",
    "load_env": "load",
    "watch_config": "monitor",
    "reload_config": "load",
    "put_obj": "send",
    "get_obj": "receive",
    "delete_obj": "delete",
    "list_objs": "list",
    "exists_obj": "verify",
    "get_size": "get",
    "manage_blob": "set",
    "manage_obj": "set",
    "manage_doc": "set",
    "manage_table": "set",
    "manage_record": "set",
    "manage_bucket": "set",
    "manage_volume": "set",
    "replicate_storage": "sync",
    "assert_cond": "verify",
    "verify_outcome": "verify",
    "run_unit": "test",
    "setup_fixture": "create",
    "teardown_fixture": "delete",
    "run_integration": "test",
    "run_benchmark": "test",
    "create_fixture": "create",
    "mock_obj": "create",
    "measure_coverage": "stats",
    "skip_test": "control",
    "report_test": "report",
    "count_elems": "count",
    "sum_vals": "calculate",
    "calc_avg": "calculate",
    "find_min": "calculate",
    "find_max": "calculate",
    "calc_median": "calculate",
    "calc_stddev": "calculate",
    "calc_trend": "calculate",
    "forecast_vals": "predict",
    "calc_correlation": "calculate",
    "cluster_data": "classify",
    "classify_data": "classify",
    "aggregate_data": "aggregate",
    "group_data": "group",
    "create_pivot": "transform",
    "detect_anomaly": "detect",
    "generate_insight": "report",
    "create_prompt": "set",
    "gen_completion": "generate",
    "gen_embedding": "embed",
    "gen_text": "generate",
    "classify_text": "classify",
    "extract_info": "extract",
    "summarize_text": "generate",
    "translate_text": "convert",
    "rank_results": "sort",
    "score_output": "score",
    "plan_actions": "plan",
    "reason_input": "reason",
    "reflect_output": "reflect",
    "evaluate_output": "evaluate",
    "learn_feedback": "learn",
    "remember_mem": "store",
    "forget_mem": "delete",
    "send_msg": "send",
    "receive_msg": "receive",
    "publish_msg": "send",
    "subscribe_topic": "subscribe",
    "unsubscribe_topic": "subscribe",
    "manage_queue": "queue",
    "manage_topic": "set",
    "manage_channel": "set",
    "broadcast_msg": "send",
    "ack_msg": "ack",
    "nack_msg": "ack",
    "retry_msg": "run",
    "deadletter_msg": "queue",
    "delay_msg": "set",
    "set_priority": "set",
    "execute_code": "execute",
    "eval_expr": "execute",
    "compile_src": "compile",
    "load_module": "load",
    "unload_module": "delete",
    "decompile_bc": "decompile",
    "register_handler": "register",
    "unregister_handler": "unregister",
    "dispatch_handler": "dispatch",
    "install_hook": "register",
    "intercept_call": "register",
    "sandbox_exec": "isolate",
    "monitor_exec": "monitor",
    "profile_exec": "monitor",
    "define_rule": "set",
    "define_policy": "set",
    "define_constraint": "set",
    "check_compliance": "verify",
    "record_violation": "log",
    "enforce_policy": "enforce",
    "waive_policy": "delete",
    "approve_req": "verify",
    "reject_req": "verify",
    "review_compliance": "scan",
    "audit_gov": "log",
    "report_gov": "report",
    "escalate_issue": "handle",
    "handle_exception": "handle",
    "log_msg": "log",
    "log_debug": "log",
    "log_info": "log",
    "log_warn": "log",
    "log_error": "log",
    "log_fatal": "log",
    "trace_exec": "log",
    "record_metric": "log",
    "log_event": "dispatch",
    "filter_records": "filter",
    "query_entries": "query",
    "flush_handlers": "sync",
    "rotate_files": "archive",
    "archive_logs": "archive",
    "gen_docs": "generate",
    "render_html": "render",
    "apply_template": "set",
    "export_docs": "export",
    "import_docs": "import",
    "create_index": "index",
    "search_docs": "search",
    "cross_reference": "link",
    "gen_changelog": "report",
    "gen_readme": "generate",
    "gen_api": "generate",
    "gen_example": "generate",
    "gen_diagram": "generate",
    "build_pkg": "build",
    "install_pkg": "install",
    "uninstall_pkg": "delete",
    "update_pkg": "update",
    "list_pkgs": "list",
    "show_info": "get",
    "show_deps": "stats",
    "resolve_deps": "resolve",
    "lock_versions": "lock",
    "publish_pkg": "send",
    "fetch_pkg": "fetch",
    "verify_pkg": "verify",
    "sign_pkg": "sign",
    "calc_checksum": "hash",
    "trigger_job": "run",
    "sched_task": "schedule",
    "run_auto": "run",
    "chain_tasks": "link",
    "branch_cond": "route",
    "loop_items": "iterate",
    "cond_exec": "verify",
    "wait_cond": "sync",
    "send_notify": "send",
    "reg_webhook": "register",
    "cron_sched": "schedule",
    "interval_sched": "schedule",
    "event_trigger": "dispatch",
    "state_machine": "run",
    "create_archive": "create",
    "extract_archive": "extract",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "list_archive": "list",
    "verify_archive": "verify",
    "split_archive": "split",
    "join_archive": "join",
    "encrypt_archive": "encrypt",
    "decrypt_archive": "decrypt",
    "index_archive": "index",
    "search_archive": "search",
    "scan_violations": "scan",
    "check_compliance": "verify",
    "report_audit": "report",
    "record_violation": "log",
    "check_status": "verify",
    "trace_audit": "trace",
    "history_audit": "list",
    "diff_audit": "compare",
    "set_baseline": "set",
    "detect_drift": "detect",
    "flag_activity": "detect",
    "escalate_finding": "handle",
    "fix_violation": "fix",
    "verify_fix": "verify",
    "check_naming": "validate",
    "check_format": "validate",
    "check_structure": "validate",
    "report_style": "report",
    "check_vbstyle": "validate",
    "fix_header": "fix",
    "fix_naming": "fix",
    "fix_format": "fix",
    "enforce_style": "enforce",
    "scan_style": "scan",
    "score_style": "score",
    "design_arch": "design",
    "review_arch": "review",
    "scan_arch": "scan",
    "identify_pattern": "analyze",
    "analyze_layer": "analyze",
    "analyze_dep": "analyze",
    "measure_coupling": "calculate",
    "measure_cohesion": "calculate",
    "measure_complexity": "calculate",
    "measure_debt": "calculate",
    "approve_arch": "verify",
    "enforce_arch": "enforce",
    "document_arch": "generate",
    "report_arch": "report",
    "baseline_arch": "set",
    "disassemble_bin": "disassemble",
    "assemble_code": "assemble",
    "decode_instr": "decode",
    "encode_instr": "encode",
    "analyze_asm": "analyze",
    "extract_opcodes": "extract",
    "extract_registers": "extract",
    "extract_jumps": "extract",
    "build_label_map": "build",
    "build_func_map": "build",
    "cross_ref_asm": "link",
    "report_asm": "report",
    "compile_src": "compile",
    "disassemble_bc": "disassemble",
    "analyze_bc": "analyze",
    "decompile_bc": "decompile",
    "extract_constants": "extract",
    "extract_names": "extract",
    "extract_code": "extract",
    "optimize_bc": "optimize",
    "patch_bc": "update",
    "inject_bc": "insert",
    "verify_bc": "verify",
    "compare_bc": "compare",
    "parse_args": "parse",
    "show_help": "report",
    "show_version": "get",
    "run_cmd": "run",
    "parse_flags": "parse",
    "parse_opts": "parse",
    "dispatch_cmd": "dispatch",
    "tab_complete": "generate",
    "cmd_history": "list",
    "manage_alias": "set",
    "pipe_output": "send",
    "redirect_output": "set",
    "handle_signal": "send",
    "exit_prog": "close",
    "encode_data": "encode",
    "decode_data": "decode",
    "serialize_obj": "serialize",
    "deserialize_obj": "deserialize",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "hash_data": "hash",
    "calc_checksum": "hash",
    "base64_codec": "encode",
    "hex_codec": "encode",
    "url_encode": "encode",
    "url_decode": "decode",
    "validate_encoded": "validate",
    "build_codegraph": "build",
    "query_codegraph": "query",
    "traverse_codegraph": "traverse",
    "get_neighbors": "get",
    "find_path": "path",
    "find_shortest": "path",
    "find_cycles": "detect",
    "check_connected": "verify",
    "get_components": "list",
    "get_topology": "sort",
    "visualize_graph": "render",
    "export_graph": "export",
    "import_graph": "import",
    "merge_graphs": "merge",
    "navigate_to": "route",
    "calc_distance": "calculate",
    "calc_route": "route",
    "orient_dir": "set",
    "get_heading": "get",
    "find_landmark": "search",
    "manage_waypoints": "set",
    "explore_area": "scan",
    "generate_map": "generate",
    "survey_area": "scan",
    "report_nav": "report",
    "calibrate_compass": "init",
    "benchmark_nav": "test",
    "to_json": "convert",
    "from_json": "convert",
    "to_yaml": "convert",
    "from_yaml": "convert",
    "to_xml": "convert",
    "from_xml": "convert",
    "to_csv": "convert",
    "from_csv": "convert",
    "to_toml": "convert",
    "to_dict": "convert",
    "to_list": "convert",
    "to_text": "convert",
    "validate_conv": "validate",
    "test_roundtrip": "verify",
    "split_code": "split",
    "extract_class": "extract",
    "extract_method": "extract",
    "merge_code": "merge",
    "extract_imports": "extract",
    "extract_header": "extract",
    "count_classes": "count",
    "count_methods": "count",
    "validate_split": "validate",
    "report_split": "report",
    "create_ctx": "create",
    "execute_kernel": "execute",
    "destroy_ctx": "delete",
    "list_devices": "list",
    "inspect_obj": "get",
    "register_mod": "register",
    "unregister_mod": "unregister",
    "get_status": "get",
    "get_history": "list",
    "report_cu": "report",
    "validate_cu": "validate",
    "benchmark_cu": "test",
    "discover_schemas": "scan",
    "introspect_db": "scan",
    "get_schema": "stats",
    "list_tables": "list",
    "list_columns": "list",
    "list_indexes": "list",
    "list_constraints": "list",
    "list_foreign_keys": "list",
    "list_triggers": "list",
    "list_stored_procs": "list",
    "list_views": "list",
    "list_functions": "list",
    "list_relationships": "list",
    "report_inv": "report",
    "connect_studio": "connect",
    "query_studio": "query",
    "browse_db": "scan",
    "edit_data": "update",
    "design_schema": "design",
    "migrate_studio": "migrate",
    "compare_schemas": "compare",
    "sync_dbs": "sync",
    "export_data": "export",
    "import_data": "import",
    "visualize_schema": "render",
    "optimize_queries": "optimize",
    "monitor_db": "monitor",
    "report_studio": "report",
    "create_obj": "create",
    "register_type": "register",
    "get_type": "get",
    "unregister_type": "unregister",
    "list_types": "list",
    "create_prototype": "create",
    "clone_obj": "copy",
    "configure_factory": "set",
    "dispose_obj": "delete",
    "validate_factory": "validate",
    "report_factory": "report",
    "read_bytes": "read",
    "write_bytes": "write",
    "close_fd": "close",
    "stat_file": "stats",
    "chmod_file": "set",
    "exists_path": "verify",
    "append_file": "write",
    "copy_file": "copy",
    "move_file": "update",
    "rename_file": "update",
    "glob_files": "search",
    "walk_tree": "scan",
    "touch_file": "create",
    "delete_file": "delete",
    "temp_file": "create",
    "split_path": "split",
    "join_path": "join",
    "create_dir": "create",
    "delete_dir": "delete",
    "list_dir": "list",
    "walk_dir": "scan",
    "get_size": "get",
    "gen_tree": "generate",
    "move_dir": "update",
    "copy_dir": "copy",
    "rename_dir": "update",
    "watch_dir": "monitor",
    "sync_dirs": "sync",
    "archive_dir": "archive",
    "compare_dirs": "compare",
    "clean_dir": "delete",
    "add_node": "add",
    "add_edge": "add",
    "remove_node": "remove",
    "remove_edge": "remove",
    "get_node": "get",
    "get_edge": "get",
    "find_path": "path",
    "traverse_graph": "traverse",
    "dfs": "traverse",
    "bfs": "traverse",
    "find_shortest": "path",
    "find_cycles": "detect",
    "topological_sort": "sort",
    "visualize_graph": "render",
    "export_graph": "export",
    "create_index": "create",
    "build_index": "build",
    "search_index": "search",
    "query_index": "query",
    "update_index": "update",
    "delete_index": "delete",
    "optimize_index": "optimize",
    "rebuild_index": "rebuild",
    "get_stats": "stats",
    "export_index": "export",
    "import_index": "import",
    "merge_index": "merge",
    "split_index": "split",
    "validate_index": "validate",
    "scan_sources": "scan",
    "parse_data": "parse",
    "load_data": "load",
    "validate_data": "validate",
    "extract_data": "extract",
    "transform_data": "transform",
    "dedupe_data": "filter",
    "enrich_data": "update",
    "classify_data": "classify",
    "tag_data": "set",
    "store_data": "store",
    "index_data": "index",
    "report_ingest": "report",
    "schedule_ingest": "schedule",
    "batch_ingest": "run",
    "get_status": "get",
    "report_cli": "report",
    "resume_ingest": "control",
    "cancel_ingest": "cancel",
    "browse_files": "scan",
    "select_files": "scan",
    "import_gui": "import",
    "preview_data": "read",
    "show_progress": "get",
    "set_settings": "set",
    "view_history": "list",
    "report_gui": "report",
    "validate_gui": "validate",
    "cancel_gui": "cancel",
    "write_entry": "write",
    "read_entries": "read",
    "query_entries": "query",
    "filter_entries": "filter",
    "search_entries": "search",
    "format_entries": "format",
    "set_level": "set",
    "set_category": "set",
    "export_log": "export",
    "rotate_files": "archive",
    "archive_logs": "archive",
    "purge_entries": "delete",
    "tail_log": "read",
    "follow_log": "read",
    "add_fact": "add",
    "query_fact": "query",
    "add_rule": "add",
    "query_rule": "query",
    "add_concept": "add",
    "query_concept": "query",
    "add_relation": "add",
    "query_relation": "query",
    "infer": "infer",
    "explain": "explain",
    "prove": "verify",
    "disprove": "verify",
    "merge_graphs": "merge",
    "export_graph": "export",
    "import_graph": "import",
    "set_confidence": "set",
    "track_source": "set",
    "hash_data": "hash",
    "encrypt_data": "encrypt",
    "decrypt_data": "decrypt",
    "authenticate_user": "authenticate",
    "authorize_user": "authorize",
    "sign_data": "sign",
    "verify_sig": "verify",
    "generate_token": "generate",
    "refresh_token": "update",
    "revoke_token": "delete",
    "check_permission": "authorize",
    "manage_roles": "set",
    "define_policy": "set",
    "audit_events": "log",
    "lockout_user": "lock",
    "reset_creds": "delete",
    "start_task": "start",
    "stop_task": "stop",
    "dispatch_task": "dispatch",
    "submit_task": "send",
    "pause_exec": "control",
    "resume_exec": "control",
    "schedule_task": "schedule",
    "pipeline_exec": "run",
    "sequence_exec": "run",
    "parallel_exec": "run",
    "retry_task": "run",
    "set_timeout": "set",
    "manage_deps": "link",
    "set_priority": "set",
    "manage_queue": "queue",
    "manage_worker": "run",
    "get_status": "get",
    "load_config": "load",
    "save_config": "save",
    "get_config": "get",
    "set_config": "set",
    "list_sections": "list",
    "delete_key": "delete",
    "validate_config": "validate",
    "merge_configs": "merge",
    "export_config": "export",
    "import_config": "import",
    "get_defaults": "get",
    "load_profile": "load",
    "load_env": "load",
    "watch_config": "monitor",
    "reload_config": "load",
    "put_obj": "send",
    "get_obj": "receive",
    "delete_obj": "delete",
    "list_objs": "list",
    "exists_obj": "verify",
    "get_size": "get",
    "manage_blob": "set",
    "manage_obj": "set",
    "manage_doc": "set",
    "manage_table": "set",
    "manage_record": "set",
    "manage_bucket": "set",
    "manage_volume": "set",
    "replicate_storage": "sync",
    "assert_cond": "verify",
    "verify_outcome": "verify",
    "run_unit": "test",
    "setup_fixture": "create",
    "teardown_fixture": "delete",
    "run_integration": "test",
    "run_benchmark": "test",
    "create_fixture": "create",
    "mock_obj": "create",
    "measure_coverage": "stats",
    "skip_test": "control",
    "report_test": "report",
    "count_elems": "count",
    "sum_vals": "calculate",
    "calc_avg": "calculate",
    "find_min": "calculate",
    "find_max": "calculate",
    "calc_median": "calculate",
    "calc_stddev": "calculate",
    "calc_trend": "calculate",
    "forecast_vals": "predict",
    "calc_correlation": "calculate",
    "cluster_data": "classify",
    "classify_data": "classify",
    "aggregate_data": "aggregate",
    "group_data": "group",
    "create_pivot": "transform",
    "detect_anomaly": "detect",
    "generate_insight": "report",
    "create_prompt": "set",
    "gen_completion": "generate",
    "gen_embedding": "embed",
    "gen_text": "generate",
    "classify_text": "classify",
    "extract_info": "extract",
    "summarize_text": "generate",
    "translate_text": "convert",
    "rank_results": "sort",
    "score_output": "score",
    "plan_actions": "plan",
    "reason_input": "reason",
    "reflect_output": "reflect",
    "evaluate_output": "evaluate",
    "learn_feedback": "learn",
    "remember_mem": "store",
    "forget_mem": "delete",
    "send_msg": "send",
    "receive_msg": "receive",
    "publish_msg": "send",
    "subscribe_topic": "subscribe",
    "unsubscribe_topic": "subscribe",
    "manage_queue": "queue",
    "manage_topic": "set",
    "manage_channel": "set",
    "broadcast_msg": "send",
    "ack_msg": "ack",
    "nack_msg": "ack",
    "retry_msg": "run",
    "deadletter_msg": "queue",
    "delay_msg": "set",
    "set_priority": "set",
    "execute_code": "execute",
    "eval_expr": "execute",
    "compile_src": "compile",
    "load_module": "load",
    "unload_module": "delete",
    "decompile_bc": "decompile",
    "register_handler": "register",
    "unregister_handler": "unregister",
    "dispatch_handler": "dispatch",
    "install_hook": "register",
    "intercept_call": "register",
    "sandbox_exec": "isolate",
    "monitor_exec": "monitor",
    "profile_exec": "monitor",
    "define_rule": "set",
    "define_policy": "set",
    "define_constraint": "set",
    "check_compliance": "verify",
    "record_violation": "log",
    "enforce_policy": "enforce",
    "waive_policy": "delete",
    "approve_req": "verify",
    "reject_req": "verify",
    "review_compliance": "scan",
    "audit_gov": "log",
    "report_gov": "report",
    "escalate_issue": "handle",
    "handle_exception": "handle",
    "log_msg": "log",
    "log_debug": "log",
    "log_info": "log",
    "log_warn": "log",
    "log_error": "log",
    "log_fatal": "log",
    "trace_exec": "log",
    "record_metric": "log",
    "log_event": "dispatch",
    "filter_records": "filter",
    "query_entries": "query",
    "flush_handlers": "sync",
    "rotate_files": "archive",
    "archive_logs": "archive",
    "gen_docs": "generate",
    "render_html": "render",
    "apply_template": "set",
    "export_docs": "export",
    "import_docs": "import",
    "create_index": "index",
    "search_docs": "search",
    "cross_reference": "link",
    "gen_changelog": "report",
    "gen_readme": "generate",
    "gen_api": "generate",
    "gen_example": "generate",
    "gen_diagram": "generate",
    "build_pkg": "build",
    "install_pkg": "install",
    "uninstall_pkg": "delete",
    "update_pkg": "update",
    "list_pkgs": "list",
    "show_info": "get",
    "show_deps": "stats",
    "resolve_deps": "resolve",
    "lock_versions": "lock",
    "publish_pkg": "send",
    "fetch_pkg": "fetch",
    "verify_pkg": "verify",
    "sign_pkg": "sign",
    "calc_checksum": "hash",
    "trigger_job": "run",
    "sched_task": "schedule",
    "run_auto": "run",
    "chain_tasks": "link",
    "branch_cond": "route",
    "loop_items": "iterate",
    "cond_exec": "verify",
    "wait_cond": "sync",
    "send_notify": "send",
    "reg_webhook": "register",
    "cron_sched": "schedule",
    "interval_sched": "schedule",
    "event_trigger": "dispatch",
    "state_machine": "run",
    "create_archive": "create",
    "extract_archive": "extract",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "list_archive": "list",
    "verify_archive": "verify",
    "split_archive": "split",
    "join_archive": "join",
    "encrypt_archive": "encrypt",
    "decrypt_archive": "decrypt",
    "index_archive": "index",
    "search_archive": "search",
    "scan_violations": "scan",
    "check_compliance": "verify",
    "report_audit": "report",
    "record_violation": "log",
    "check_status": "verify",
    "trace_audit": "trace",
    "history_audit": "list",
    "diff_audit": "compare",
    "set_baseline": "set",
    "detect_drift": "detect",
    "flag_activity": "detect",
    "escalate_finding": "handle",
    "fix_violation": "fix",
    "verify_fix": "verify",
    "check_naming": "validate",
    "check_format": "validate",
    "check_structure": "validate",
    "report_style": "report",
    "check_vbstyle": "validate",
    "fix_header": "fix",
    "fix_naming": "fix",
    "fix_format": "fix",
    "enforce_style": "enforce",
    "scan_style": "scan",
    "score_style": "score",
    "design_arch": "design",
    "review_arch": "review",
    "scan_arch": "scan",
    "identify_pattern": "analyze",
    "analyze_layer": "analyze",
    "analyze_dep": "analyze",
    "measure_coupling": "calculate",
    "measure_cohesion": "calculate",
    "measure_complexity": "calculate",
    "measure_debt": "calculate",
    "approve_arch": "verify",
    "enforce_arch": "enforce",
    "document_arch": "generate",
    "report_arch": "report",
    "baseline_arch": "set",
    "disassemble_bin": "disassemble",
    "assemble_code": "assemble",
    "decode_instr": "decode",
    "encode_instr": "encode",
    "analyze_asm": "analyze",
    "extract_opcodes": "extract",
    "extract_registers": "extract",
    "extract_jumps": "extract",
    "build_label_map": "build",
    "build_func_map": "build",
    "cross_ref_asm": "link",
    "report_asm": "report",
    "compile_src": "compile",
    "disassemble_bc": "disassemble",
    "analyze_bc": "analyze",
    "decompile_bc": "decompile",
    "extract_constants": "extract",
    "extract_names": "extract",
    "extract_code": "extract",
    "optimize_bc": "optimize",
    "patch_bc": "update",
    "inject_bc": "insert",
    "verify_bc": "verify",
    "compare_bc": "compare",
    "parse_args": "parse",
    "show_help": "report",
    "show_version": "get",
    "run_cmd": "run",
    "parse_flags": "parse",
    "parse_opts": "parse",
    "dispatch_cmd": "dispatch",
    "tab_complete": "generate",
    "cmd_history": "list",
    "manage_alias": "set",
    "pipe_output": "send",
    "redirect_output": "set",
    "handle_signal": "send",
    "exit_prog": "close",
    "encode_data": "encode",
    "decode_data": "decode",
    "serialize_obj": "serialize",
    "deserialize_obj": "deserialize",
    "compress_data": "compress",
    "decompress_data": "decompress",
    "hash_data": "hash",
    "calc_checksum": "hash",
    "base64_codec": "encode",
    "hex_codec": "encode",
    "url_encode": "encode",
    "url_decode": "decode",
    "validate_encoded": "validate",
    "build_codegraph": "build",
    "query_codegraph": "query",
    "traverse_codegraph": "traverse",
    "get_neighbors": "get",
    "find_path": "path",
    "find_shortest": "path",
    "find_cycles": "detect",
    "check_connected": "verify",
    "get_components": "list",
    "get_topology": "sort",
    "visualize_graph": "render",
    "export_graph": "export",
    "import_graph": "import",
    "merge_graphs": "merge",
    "navigate_to": "route",
    "calc_distance": "calculate",
    "calc_route": "route",
    "orient_dir": "set",
    "get_heading": "get",
    "find_landmark": "search",
    "manage_waypoints": "set",
    "explore_area": "scan",
    "generate_map": "generate",
    "survey_area": "scan",
    "report_nav": "report",
    "calibrate_compass": "init",
    "benchmark_nav": "test",
    "to_json": "convert",
    "from_json": "convert",
    "to_yaml": "convert",
    "from_yaml": "convert",
    "to_xml": "convert",
    "from_xml": "convert",
    "to_csv": "convert",
    "from_csv": "convert",
    "to_toml": "convert",
    "to_dict": "convert",
    "to_list": "convert",
    "to_text": "convert",
    "validate_conv": "validate",
    "test_roundtrip": "verify",
    "split_code": "split",
    "extract_class": "extract",
    "extract_method": "extract",
    "merge_code": "merge",
    "extract_imports": "extract",
    "extract_header": "extract",
    "count_classes": "count",
    "count_methods": "count",
    "validate_split": "validate",
    "report_split": "report",
    "create_ctx": "create",
    "execute_kernel": "execute",
    "destroy_ctx": "delete",
    "list_devices": "list",
    "inspect_obj": "get",
    "register_mod": "register",
    "unregister_mod": "unregister",
    "get_status": "get",
    "get_history": "list",
    "report_cu": "report",
    "validate_cu": "validate",
    "benchmark_cu": "test",
    "discover_schemas": "scan",
    "introspect_db": "scan",
    "get_schema": "stats",
    "list_tables": "list",
    "list_columns": "list",
    "list_indexes": "list",
    "list_constraints": "list",
    "list_foreign_keys": "list",
    "list_triggers": "list",
    "list_stored_procs": "list",
    "list_views": "list",
    "list_functions": "list",
    "list_relationships": "list",
    "report_inv": "report",
    "connect_studio": "connect",
    "query_studio": "query",
    "browse_db": "scan",
    "edit_data": "update",
    "design_schema": "design",
    "migrate_studio": "migrate",
    "compare_schemas": "compare",
    "sync_dbs": "sync",
    "export_data": "export",
    "import_data": "import",
    "visualize_schema": "render",
    "optimize_queries": "optimize",
    "monitor_db": "monitor",
    "report_studio": "report",
    "create_obj": "create",
    "register_type": "register",
    "get_type": "get",
    "unregister_type": "unregister",
    "list_types": "list",
    "create_prototype": "create",
    "clone_obj": "copy",
    "configure_factory": "set",
    "dispose_obj": "delete",
    "validate_factory": "validate",
    "report_factory": "report",
}


def canonical_name(method_name):
    """Resolve a method name to its canonical primitive name."""
    return ALIAS_CANONICAL.get(method_name, method_name)


def make_pascal(domain):
    return "".join(w.capitalize() for w in domain.split("_"))


def generate_vbstyle_stub(domain, canonical):
    """Generate VBStyle stub using canonical primitive name."""
    safe = canonical
    if keyword.iskeyword(canonical):
        safe = f"{canonical}_impl"
    pascal = make_pascal(domain)
    upper = canonical.upper()
    return (
        f'class Dom{pascal}:\n'
        f'    def __init__(self, mem=None, db=None, param=None):\n'
        f'        self.state = {{"config": {{}}, "results": []}}\n'
        f'    def {safe}(self, params=None):\n'
        f'        params = params or {{}}\n'
        f'        try:\n'
        f'            result = {{"domain": "{domain}", "method": "{canonical}", "params": params}}\n'
        f'            return (1, result, None)\n'
        f'        except Exception as e:\n'
        f'            return (0, {{}}, ("{upper}_ERROR", str(e), 0))'
    )


def main():
    # ---------- Step 1: Merge domains ----------
    merged = defaultdict(lambda: {"core": [], "extended": [], "control": [], "edge": [],
                                   "sources": set(), "confidence_scores": []})

    for domain, info in EXTRACTED_DOMAINS.items():
        target = MERGE_MAP.get(domain, domain)
        for layer in ("core", "extended", "control", "edge"):
            for m in info[layer]:
                merged[target][layer].append({
                    "name": m["name"],
                    "canonical": canonical_name(m["name"]),
                    "purpose": m["purpose"],
                    "source": m["source"],
                })
        merged[target]["sources"].update(info["sources"])
        merged[target]["confidence_scores"].append(info["confidence_score"])

    # ---------- Step 2: Deduplicate within each merged domain ----------
    for domain in merged:
        seen_canonical = set()
        for layer in ("core", "extended", "control", "edge"):
            unique = []
            for m in merged[domain][layer]:
                key = m["canonical"]
                if key not in seen_canonical:
                    seen_canonical.add(key)
                    m["code"] = generate_vbstyle_stub(domain, m["canonical"])
                    unique.append(m)
            merged[domain][layer] = unique

    # ---------- Step 3: Extract shared primitives ----------
    # Count canonical name frequency across domains
    canonical_domains = defaultdict(set)
    for domain in merged:
        for layer in ("core", "extended", "control", "edge"):
            for m in merged[domain][layer]:
                canonical_domains[m["canonical"]].add(domain)

    shared_primitives = {}
    domain_specific = {}
    for canon, doms in canonical_domains.items():
        if len(doms) >= SHARED_PRIMITIVE_THRESHOLD:
            shared_primitives[canon] = sorted(doms)
        else:
            domain_specific[canon] = sorted(doms)

    # Remove shared primitives from domain layers, BUT keep at least 1 core method
    # to preserve domain identity (even if it's a shared primitive)
    for domain in merged:
        all_methods = []
        for layer in ("core", "extended", "control", "edge"):
            all_methods.extend(merged[domain][layer])
        domain_specific_methods = [m for m in all_methods if m["canonical"] not in shared_primitives]

        # If no domain-specific methods remain, keep the first 2 shared primitives as core
        if not domain_specific_methods:
            kept = all_methods[:2]
            remaining = all_methods[2:]
            merged[domain]["core"] = kept
            merged[domain]["extended"] = []
            merged[domain]["control"] = []
            merged[domain]["edge"] = []
        else:
            for layer in ("core", "extended", "control", "edge"):
                merged[domain][layer] = [m for m in merged[domain][layer]
                                         if m["canonical"] not in shared_primitives]

    # Ensure no empty core — move from extended/control if needed
    for domain in merged:
        if not merged[domain]["core"]:
            if merged[domain]["extended"]:
                merged[domain]["core"].append(merged[domain]["extended"].pop(0))
            elif merged[domain]["control"]:
                merged[domain]["core"].append(merged[domain]["control"].pop(0))
            elif merged[domain]["edge"]:
                merged[domain]["core"].append(merged[domain]["edge"].pop(0))

    # ---------- Step 4: Compute stats ----------
    total_domain_specific = 0
    for domain in merged:
        for layer in ("core", "extended", "control", "edge"):
            total_domain_specific += len(merged[domain][layer])

    total_shared = len(shared_primitives)
    total_unique_behaviors = total_domain_specific + total_shared

    # ---------- Step 5: Write output file ----------
    output_path = os.path.join(os.path.dirname(__file__), "normalized_domain_closure.py")

    lines = [
        '"""Normalized domain closure — Level 2.',
        '',
        'Produced by normalize_closure.py from domain_extraction_results.py.',
        '',
        'Transformations applied:',
        '  1. Merged 6 overlapping domain pairs (index+wws_index, logging+log, etc.)',
        f'  2. Resolved {len(ALIAS_CANONICAL)} aliases to canonical primitive names',
        f'  3. Extracted {total_shared} shared primitives (appear in >={SHARED_PRIMITIVE_THRESHOLD} domains)',
        '  4. Deduplicated methods within each domain',
        '',
        f'Original: 58 domains, 873 method entries',
        f'Normalized: {len(merged)} domains, {total_domain_specific} domain-specific methods + {total_shared} shared primitives = {total_unique_behaviors} unique behaviors',
        '"""',
        '',
        'NORMALIZED_DOMAINS = {',
    ]

    for i, (domain, info) in enumerate(sorted(merged.items())):
        avg_conf = sum(info["confidence_scores"]) / len(info["confidence_scores"])
        sources = sorted(info["sources"])
        lines.append(f'    "{domain}": {{')
        for layer in ("core", "extended", "control", "edge"):
            lines.append(f'        "{layer}": [')
            for m in info[layer]:
                lines.append(f'            {{"name": "{m["name"]}", "canonical": "{m["canonical"]}", "purpose": "{m["purpose"]}", "source": "{m["source"]}", "code": {repr(m["code"])}}},')
            lines.append('        ],')
        lines.append(f'        "confidence_score": {avg_conf:.2f},')
        lines.append(f'        "sources": {sources!r},')
        comma = "," if i < len(merged) - 1 else ""
        lines.append(f'    }}{comma}')

    lines.append('}')
    lines.append('')
    lines.append('SHARED_PRIMITIVES = {')
    for canon, doms in sorted(shared_primitives.items()):
        lines.append(f'    "{canon}": {doms!r},')
    lines.append('}')
    lines.append('')
    lines.append(f'TOTAL_UNIQUE_BEHAVIORS = {total_unique_behaviors}')
    lines.append(f'TOTAL_SHARED_PRIMITIVES = {total_shared}')
    lines.append(f'TOTAL_DOMAIN_SPECIFIC = {total_domain_specific}')
    lines.append(f'TOTAL_DOMAINS = {len(merged)}')
    lines.append('')

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {output_path}")
    print(f"Domains: {len(merged)} (was 58, merged {58 - len(merged)})")
    print(f"Domain-specific methods: {total_domain_specific}")
    print(f"Shared primitives: {total_shared}")
    print(f"Total unique behaviors: {total_unique_behaviors}")
    print(f"Reduction: 873 -> {total_unique_behaviors} ({(1 - total_unique_behaviors/873)*100:.1f}% removed)")


if __name__ == "__main__":
    main()
