"""
Graph data for Web domain.
Generated by DomainEngine. Consumed by the 8 graph viewers:
  Plan, Spec, Flow, Lifecycle, Dep, Error, Orch, Gap
"""

GRAPH_CLASSES = [
    ("Browser", "class", ["open", "close", "refresh", "navigate", "back", "forward"], "Browser control component"),
    ("Request", "class", ["get", "post", "put", "delete", "patch", "head", "options"], "HTTP request builder"),
    ("Response", "class", ["status", "headers", "body", "json", "text", "bytes"], "HTTP response handler"),
    ("Session", "class", ["create", "restore", "save", "clear", "info"], "Session management"),
    ("Cookie", "class", ["set", "get", "delete", "list", "clear"], "Cookie jar management"),
    ("Header", "class", ["set", "get", "remove", "list", "parse"], "HTTP header management"),
    ("URL", "class", ["parse", "build", "encode", "decode", "resolve", "normalize"], "URL parsing and building"),
    ("HTTP", "class", ["connect", "send", "receive", "close"], "HTTP protocol handler"),
    ("HTTPS", "class", ["connect", "send", "receive", "close"], "HTTPS protocol handler"),
    ("Download", "class", ["file", "stream", "resume", "cancel", "progress"], "Download manager"),
    ("Upload", "class", ["file", "stream", "multipart", "cancel", "progress"], "Upload manager"),
    ("Cache", "class", ["read", "write", "clear", "invalidate", "size", "keys"], "Response cache"),
    ("Parser", "class", ["html", "json", "xml", "yaml", "rss", "sitemap"], "Multi-format parser"),
    ("Scraper", "class", ["fetch", "extract", "mirror", "download", "status"], "Web scraper with fallback"),
    ("Crawler", "class", ["crawl", "checkrobots", "queue", "visited", "reset"], "Web crawler"),
    ("Spider", "class", ["crawl", "follow", "extract", "store", "schedule"], "Spider for systematic crawling"),
    ("Auth", "class", ["basic", "bearer", "oauth", "jwt", "apikey", "verify"], "Authentication handler"),
    ("Proxy", "class", ["set", "get", "remove", "list", "test"], "Proxy configuration"),
    ("DNS", "class", ["resolve", "lookup", "reverse", "records"], "DNS resolver"),
    ("SSL", "class", ["verify", "info", "pin", "fingerprint"], "SSL/TLS certificate handler"),
    ("RateLimiter", "class", ["check", "wait", "reset", "config"], "Rate limiting"),
    ("Retry", "class", ["attempt", "backoff", "reset", "config"], "Retry with backoff"),
    ("Redirect", "class", ["follow", "chain", "resolve", "config"], "Redirect following"),
    ("Compression", "class", ["compress", "decompress", "gzip", "deflate", "brotli"], "Content compression"),
    ("Robots", "class", ["parse", "check", "allowed", "disallowed", "sitemap"], "Robots.txt parser"),
    ("Monitor", "class", ["start", "stop", "log", "metrics", "alert"], "Web monitoring"),
    ("Security", "class", ["cors", "csp", "hsts", "csrf", "xss", "fingerprint"], "Web security policies"),
    ("Validator", "class", ["url", "email", "html", "json", "xml", "schema"], "Input validation"),
]

GRAPH_EDGES = [
    ("Browser", "Request", "USES"),
    ("Browser", "Response", "USES"),
    ("Browser", "Cookie", "USES"),
    ("Browser", "Session", "USES"),
    ("Browser", "Cache", "USES"),
    ("Browser", "Parser", "USES"),
    ("Request", "Header", "USES"),
    ("Request", "Auth", "USES"),
    ("Request", "URL", "USES"),
    ("Request", "Cookie", "FEEDS"),
    ("Request", "HTTP", "TRIGGERS"),
    ("Request", "HTTPS", "TRIGGERS"),
    ("HTTP", "Response", "FEEDS"),
    ("HTTPS", "Response", "FEEDS"),
    ("Response", "Parser", "FEEDS"),
    ("Response", "Cache", "FEEDS"),
    ("Scraper", "Request", "USES"),
    ("Scraper", "Parser", "USES"),
    ("Scraper", "Download", "USES"),
    ("Crawler", "Scraper", "WRAPS"),
    ("Crawler", "Robots", "USES"),
    ("Crawler", "RateLimiter", "USES"),
    ("Spider", "Crawler", "WRAPS"),
    ("Spider", "Cache", "USES"),
    ("Download", "Retry", "USES"),
    ("Download", "Redirect", "USES"),
    ("Upload", "Retry", "USES"),
    ("Auth", "SSL", "ENABLES"),
    ("Proxy", "HTTP", "WRAPS"),
    ("Proxy", "HTTPS", "WRAPS"),
    ("DNS", "URL", "FEEDS"),
    ("Monitor", "Validator", "MEASURES"),
    ("Security", "Validator", "USES"),
    ("Compression", "HTTP", "ENABLES"),
]

GRAPH_FLOWS = {
    "Browser": [
        ("call", "Request -- build HTTP request"),
        ("step", "Send via HTTP/HTTPS"),
        ("call", "Response -- receive response"),
        ("call", "Parser -- parse response body"),
        ("call", "Cache -- store response"),
        ("call", "Cookie -- update cookies"),
    ],
    "Scraper": [
        ("call", "Request -- fetch URL"),
        ("step", "Fallback to wget if urllib fails"),
        ("call", "Parser -- extract content"),
        ("call", "Download -- save to disk"),
    ],
    "Crawler": [
        ("call", "Robots -- check allowed"),
        ("call", "RateLimiter -- wait if needed"),
        ("call", "Scraper -- fetch page"),
        ("step", "Extract links from page"),
        ("step", "Queue new links"),
        ("step", "Mark URL as visited"),
    ],
}

GRAPH_CATEGORIES = {
    "CRUD": ["Browser", "Request", "Response", "Download", "Upload", "Cache", "Cookie", "Session"],
    "TRANSFORM": ["Parser", "Compression", "Redirect", "URL"],
    "SECURITY": ["Auth", "SSL", "Security", "Validator"],
    "UTILITY": ["Scraper", "Crawler", "Spider", "Proxy", "DNS", "Robots", "RateLimiter", "Retry", "Monitor"],
    "META": ["Header", "HTTP", "HTTPS"],
}

GRAPH_DOMAIN_NAME = "Web"
GRAPH_DOMAIN_FILE = "dom_web.py"