#!/usr/bin/env python3
"""Config — auto-generated by config_extractor.py"""

from pathlib import Path

BASE_DIR = Path(__file__).parent

# Sources: style_db_v2.py, style_engine_v2.py, qt_renderer_v2.py, ui_db_v4.py, gui_decision_engine.py

# ── Module Constants ───────────────────────────────────────────
DB_PATH_V2 = 'styles_v2.db'
DB_PATH_V4 = 'ui_v4.db'

# ── Default Parameters ────────────────────────────────────────
DEFAULT_ORDER_INDEX = 0

# ── Fallback Defaults (from .get() calls) ─────────────────────
FALLBACK_COLOR_BORDER = '#000000'
FALLBACK_FORMAT_BORDER_WIDTH = 1
FALLBACK_MATCH_REASON = 'Best fit for context'
FALLBACK_PRIORITY = 1
FALLBACK_SCORE = 'N/A'

# ── Hardcoded Strings ─────────────────────────────────────────
PATH_# SIMPLE IF_THEN_ELSE PARSING
        IF  = '# Simple IF/THEN/ELSE parsing\n        if '
PATH_N_A = 'N/A'
TABLE_BASE_SCORE = 'base_score'
TABLE_CONDITION_EXPRESSION = 'condition_expression'
BOOL_FALSE = 'false'
TABLE_GUI_DECISION = 'gui_decision'
TABLE_GUI_UI_DB = 'gui_ui_db'
TABLE_MATCH_REASON = 'match_reason'
TABLE_MAX_SCORE = 'max_score'
TABLE_RESOLUTION_EXPRESSION = 'resolution_expression'
TABLE_SCORE_EXPRESSION = 'score_expression'
DB_PATH_TOKEN_REGISTRY = 'token_registry.db'
BOOL_TRUE = 'true'
SQL_FILE_UI_DB_V4 = 'ui_db_v4.sql'

# ── Hardcoded Numbers ────────────────────────────────────────
SIZE_0 = 0
SIZE_1 = 1
SIZE_2 = 2
SIZE_4 = 4
SIZE_8 = 8
SIZE_20 = 20
SIZE_100 = 100
PORT_2026 = 2026
NUM_0_3 = 0.3
NUM_0_5 = 0.5

# ── Classes ───────────────────────────────────────────────────
# StyleDBV2: __init__, _init_db, register_object, set_property, get_property, get_all_properties, get_objects_by_type, close
# StyleEngineV2: __init__, apply_selector, get_style, update_property
# QtStyleRendererV2: __init__, apply_to_widget, get_painter_style
# UIDBV4: __init__, _init_db, register_component, get_component, create_node, get_node, get_children, create_screen, get_screen, close
# GUIDecisionEngine: __init__, _load_architecture_learnings, _load_decision_principles, _validate_against_principles, decide_component, _retrieve_candidates, _apply_hard_filter, _apply_when_rules, _resolve_conflicts, _evaluate_resolution, _score_candidates, _evaluate_score, _evaluate_condition, _output_decision, _no_valid_decision, close

